In [45]:
import pandas as pd


data_arts_humanities_1 = [
    {"Código": "0001", "TITULACIONES DE GRADO": "Arqueología", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0002", "TITULACIONES DE GRADO": "Bellas Artes", "Grupo 1 Ord.": "10.115", "University": "Universidad Complutense de Madrid"},
    {"Código": "0019", "TITULACIONES DE GRADO": "Ciencias de las Religiones", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0004", "TITULACIONES DE GRADO": "Conservación y Restauración del Patrimonio Cultural", "Grupo 1 Ord.": "10.100", "University": "Universidad Complutense de Madrid"},
    {"Código": "0005", "TITULACIONES DE GRADO": "Diseño", "Grupo 1 Ord.": "11.818", "University": "Universidad Complutense de Madrid"},
    {"Código": "0006", "TITULACIONES DE GRADO": "Español: Lengua y Literatura", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0007", "TITULACIONES DE GRADO": "Estudios Ingleses", "Grupo 1 Ord.": "7.578", "University": "Universidad Complutense de Madrid"},
    {"Código": "0008", "TITULACIONES DE GRADO": "Estudios Semíticos e Islámicos", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0020", "TITULACIONES DE GRADO": "Estudios Teatrales", "Grupo 1 Ord.": "5.982", "University": "Universidad Complutense de Madrid"},
    {"Código": "0009", "TITULACIONES DE GRADO": "Filología Clásica", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0010", "TITULACIONES DE GRADO": "Filosofía", "Grupo 1 Ord.": "7.454", "University": "Universidad Complutense de Madrid"},
    {"Código": "0011", "TITULACIONES DE GRADO": "Historia", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0012", "TITULACIONES DE GRADO": "Historia del Arte", "Grupo 1 Ord.": "10.346", "University": "Universidad Complutense de Madrid"},
    {"Código": "0013", "TITULACIONES DE GRADO": "Lenguas Modernas y sus Literaturas", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0015", "TITULACIONES DE GRADO": "Lingüística y Lenguas Aplicadas", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0018", "TITULACIONES DE GRADO": "Literatura General y Comparada", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0016", "TITULACIONES DE GRADO": "Musicología", "Grupo 1 Ord.": "6.084", "University": "Universidad Complutense de Madrid"},
    {"Código": "0014", "TITULACIONES DE GRADO": "Traducción e Interpretación", "Grupo 1 Ord.": "7.127", "University": "Universidad Complutense de Madrid"}
]


df_arts_humanities_1 = pd.DataFrame(data_arts_humanities_1)

df_arts_humanities_1

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0001,Arqueología,5.000,Universidad Complutense de Madrid
1,0002,Bellas Artes,10.115,Universidad Complutense de Madrid
2,0019,Ciencias de las Religiones,5.000,Universidad Complutense de Madrid
3,0004,Conservación y Restauración del Patrimonio Cul...,10.100,Universidad Complutense de Madrid
4,0005,Diseño,11.818,Universidad Complutense de Madrid
5,0006,Español: Lengua y Literatura,5.000,Universidad Complutense de Madrid
6,0007,Estudios Ingleses,7.578,Universidad Complutense de Madrid
7,0008,Estudios Semíticos e Islámicos,5.000,Universidad Complutense de Madrid
8,0020,Estudios Teatrales,5.982,Universidad Complutense de Madrid
9,0009,Filología Clásica,5.000,Universidad Complutense de Madrid
10,0010,Filosofía,7.454,Universidad Complutense de Madrid
11,0011,Historia,5.000,Universidad Complutense de Madrid
12,0012,Historia del Arte,10.346,Universidad Complutense de Madrid
13,0013,Lenguas Modernas y sus Literaturas,5.000,Universidad Complutense de Madrid
14,0015,Lingüística y Lenguas Aplicadas,5.000,Universidad Complutense de Madrid
15,0018,Literatura General y Comparada,5.000,Universidad Complutense de Madrid
16,0016,Musicología,6.084,Universidad Complutense de Madrid
17,0014,Traducción e Interpretación,7.127,Universidad Complutense de Madrid

In [46]:
data_sciences2 = [
    {"Código": "0030", "TITULACIONES DE GRADO": "Biología", "Grupo 1 Ord.": "10.339", "University": "Universidad Complutense de Madrid"},
    {"Código": "0031", "TITULACIONES DE GRADO": "Bioquímica", "Grupo 1 Ord.": "12.523", "University": "Universidad Complutense de Madrid"},
    {"Código": "0037", "TITULACIONES DE GRADO": "Ciencia y Tecnología de los Alimentos", "Grupo 1 Ord.": "8.728", "University": "Universidad Complutense de Madrid"},
    {"Código": "0032", "TITULACIONES DE GRADO": "Física", "Grupo 1 Ord.": "12.060", "University": "Universidad Complutense de Madrid"},
    {"Código": "0033", "TITULACIONES DE GRADO": "Geología", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0034", "TITULACIONES DE GRADO": "Matemáticas", "Grupo 1 Ord.": "12.300", "University": "Universidad Complutense de Madrid"},
    {"Código": "0038", "TITULACIONES DE GRADO": "Matemáticas y Ciencia de Datos", "Grupo 1 Ord.": "11.965", "University": "Universidad Complutense de Madrid"},
    {"Código": "0036", "TITULACIONES DE GRADO": "Química", "Grupo 1 Ord.": "10.136", "University": "Universidad Complutense de Madrid"}
]


df_sciences2 = pd.DataFrame(data_sciences2)

df_sciences2

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0030,Biología,10.339,Universidad Complutense de Madrid
1,0031,Bioquímica,12.523,Universidad Complutense de Madrid
2,0037,Ciencia y Tecnología de los Alimentos,8.728,Universidad Complutense de Madrid
3,0032,Física,12.060,Universidad Complutense de Madrid
4,0033,Geología,5.000,Universidad Complutense de Madrid
5,0034,Matemáticas,12.300,Universidad Complutense de Madrid
6,0038,Matemáticas y Ciencia de Datos,11.965,Universidad Complutense de Madrid
7,0036,Química,10.136,Universidad Complutense de Madrid

In [47]:
data_health_sciences3 = [
    {"Código": "0050", "TITULACIONES DE GRADO": "Enfermería", "Grupo 1 Ord.": "11.774", "University": "Universidad Complutense de Madrid"},
    {"Código": "0051", "TITULACIONES DE GRADO": "Farmacia", "Grupo 1 Ord.": "11.784", "University": "Universidad Complutense de Madrid"},
    {"Código": "0052", "TITULACIONES DE GRADO": "Fisioterapia", "Grupo 1 Ord.": "11.678", "University": "Universidad Complutense de Madrid"},
    {"Código": "0053", "TITULACIONES DE GRADO": "Logopedia", "Grupo 1 Ord.": "9.475", "University": "Universidad Complutense de Madrid"},
    {"Código": "0054", "TITULACIONES DE GRADO": "Medicina", "Grupo 1 Ord.": "13.265", "University": "Universidad Complutense de Madrid"},
    {"Código": "0055", "TITULACIONES DE GRADO": "Nutrición Humana y Dietética", "Grupo 1 Ord.": "10.462", "University": "Universidad Complutense de Madrid"},
    {"Código": "0056", "TITULACIONES DE GRADO": "Odontología", "Grupo 1 Ord.": "12.777", "University": "Universidad Complutense de Madrid"},
    {"Código": "0057", "TITULACIONES DE GRADO": "Óptica y Optometría", "Grupo 1 Ord.": "7.667", "University": "Universidad Complutense de Madrid"},
    {"Código": "0058", "TITULACIONES DE GRADO": "Podología", "Grupo 1 Ord.": "9.110", "University": "Universidad Complutense de Madrid"},
    {"Código": "0059", "TITULACIONES DE GRADO": "Psicología", "Grupo 1 Ord.": "10.289", "University": "Universidad Complutense de Madrid"},
    {"Código": "0060", "TITULACIONES DE GRADO": "Terapia Ocupacional", "Grupo 1 Ord.": "9.536", "University": "Universidad Complutense de Madrid"},
    {"Código": "0061", "TITULACIONES DE GRADO": "Veterinaria", "Grupo 1 Ord.": "12.075", "University": "Universidad Complutense de Madrid"}
]


df_health_sciences3 = pd.DataFrame(data_health_sciences3)

df_health_sciences3

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0050,Enfermería,11.774,Universidad Complutense de Madrid
1,0051,Farmacia,11.784,Universidad Complutense de Madrid
2,0052,Fisioterapia,11.678,Universidad Complutense de Madrid
3,0053,Logopedia,9.475,Universidad Complutense de Madrid
4,0054,Medicina,13.265,Universidad Complutense de Madrid
5,0055,Nutrición Humana y Dietética,10.462,Universidad Complutense de Madrid
6,0056,Odontología,12.777,Universidad Complutense de Madrid
7,0057,Óptica y Optometría,7.667,Universidad Complutense de Madrid
8,0058,Podología,9.110,Universidad Complutense de Madrid
9,0059,Psicología,10.289,Universidad Complutense de Madrid
10,0060,Terapia Ocupacional,9.536,Universidad Complutense de Madrid
11,0061,Veterinaria,12.075,Universidad Complutense de Madrid

In [48]:
data_engineering_architecture4 = [
    {"Código": "0088", "TITULACIONES DE GRADO": "Desarrollo de Videojuegos", "Grupo 1 Ord.": "10.264", "University": "Universidad Complutense de Madrid"},
    {"Código": "0080", "TITULACIONES DE GRADO": "Ingeniería de Computadores", "Grupo 1 Ord.": "9.689", "University": "Universidad Complutense de Madrid"},
    {"Código": "0089", "TITULACIONES DE GRADO": "Ingeniería de Datos e Inteligencia Artificial", "Grupo 1 Ord.": "12.678", "University": "Universidad Complutense de Madrid"},
    {"Código": "0086", "TITULACIONES DE GRADO": "Ingeniería de Materiales", "Grupo 1 Ord.": "8.886", "University": "Universidad Complutense de Madrid"},
    {"Código": "0081", "TITULACIONES DE GRADO": "Ingeniería del Software", "Grupo 1 Ord.": "10.400", "University": "Universidad Complutense de Madrid"},
    {"Código": "0087", "TITULACIONES DE GRADO": "Ingeniería Electrónica de Comunicaciones", "Grupo 1 Ord.": "8.867", "University": "Universidad Complutense de Madrid"},
    {"Código": "0083", "TITULACIONES DE GRADO": "Ingeniería Geológica", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0082", "TITULACIONES DE GRADO": "Ingeniería Informática", "Grupo 1 Ord.": "10.914", "University": "Universidad Complutense de Madrid"},
    {"Código": "0084", "TITULACIONES DE GRADO": "Ingeniería Matemática", "Grupo 1 Ord.": "12.491", "University": "Universidad Complutense de Madrid"},
    {"Código": "0085", "TITULACIONES DE GRADO": "Ingeniería Química", "Grupo 1 Ord.": "11.154", "University": "Universidad Complutense de Madrid"}
]


df_engineering_architecture4 = pd.DataFrame(data_engineering_architecture4)


df_engineering_architecture4

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0088,Desarrollo de Videojuegos,10.264,Universidad Complutense de Madrid
1,0080,Ingeniería de Computadores,9.689,Universidad Complutense de Madrid
2,0089,Ingeniería de Datos e Inteligencia Artificial,12.678,Universidad Complutense de Madrid
3,0086,Ingeniería de Materiales,8.886,Universidad Complutense de Madrid
4,0081,Ingeniería del Software,10.400,Universidad Complutense de Madrid
5,0087,Ingeniería Electrónica de Comunicaciones,8.867,Universidad Complutense de Madrid
6,0083,Ingeniería Geológica,5.000,Universidad Complutense de Madrid
7,0082,Ingeniería Informática,10.914,Universidad Complutense de Madrid
8,0084,Ingeniería Matemática,12.491,Universidad Complutense de Madrid
9,0085,Ingeniería Química,11.154,Universidad Complutense de Madrid

In [49]:
data_social_sciences_law5 = [
    {"Código": "0100", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "10.385", "University": "Universidad Complutense de Madrid"},
    {"Código": "0128", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (en inglés)", "Grupo 1 Ord.": "11.157", "University": "Universidad Complutense de Madrid"},
    {"Código": "0101", "TITULACIONES DE GRADO": "Antropología Social y Cultural", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0125", "TITULACIONES DE GRADO": "Ciencia de los Datos Aplicada", "Grupo 1 Ord.": "11.304", "University": "Universidad Complutense de Madrid"},
    {"Código": "0102", "TITULACIONES DE GRADO": "Ciencias Políticas", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0103", "TITULACIONES DE GRADO": "Comercio", "Grupo 1 Ord.": "8.261", "University": "Universidad Complutense de Madrid"},
    {"Código": "0104", "TITULACIONES DE GRADO": "Comunicación Audiovisual", "Grupo 1 Ord.": "10.486", "University": "Universidad Complutense de Madrid"},
    {"Código": "0126", "TITULACIONES DE GRADO": "Criminología", "Grupo 1 Ord.": "11.599", "University": "Universidad Complutense de Madrid"},
    {"Código": "0106", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "8.875", "University": "Universidad Complutense de Madrid"},
    {"Código": "0108", "TITULACIONES DE GRADO": "Economía", "Grupo 1 Ord.": "9.211", "University": "Universidad Complutense de Madrid"},
    {"Código": "0129", "TITULACIONES DE GRADO": "Economía (en inglés)", "Grupo 1 Ord.": "10.250", "University": "Universidad Complutense de Madrid"},
    {"Código": "0109", "TITULACIONES DE GRADO": "Educación Social", "Grupo 1 Ord.": "8.399", "University": "Universidad Complutense de Madrid"},
    {"Código": "0110", "TITULACIONES DE GRADO": "Estadística Aplicada", "Grupo 1 Ord.": "9.111", "University": "Universidad Complutense de Madrid"},
    {"Código": "0127", "TITULACIONES DE GRADO": "Finanzas, Banca y Seguros", "Grupo 1 Ord.": "9.828", "University": "Universidad Complutense de Madrid"},
    {"Código": "0111", "TITULACIONES DE GRADO": "Geografía y Ordenación del Territorio", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0112", "TITULACIONES DE GRADO": "Gestión y Administración Pública", "Grupo 1 Ord.": "5.011", "University": "Universidad Complutense de Madrid"},
    {"Código": "0114", "TITULACIONES DE GRADO": "Información y Documentación", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0115", "TITULACIONES DE GRADO": "Maestro de Educación Infantil", "Grupo 1 Ord.": "9.460", "University": "Universidad Complutense de Madrid"},
    {"Código": "0116", "TITULACIONES DE GRADO": "Maestro de Educación Primaria", "Grupo 1 Ord.": "10.511", "University": "Universidad Complutense de Madrid"},
    {"Código": "0117", "TITULACIONES DE GRADO": "Pedagogía", "Grupo 1 Ord.": "9.200", "University": "Universidad Complutense de Madrid"},
    {"Código": "0118", "TITULACIONES DE GRADO": "Periodismo", "Grupo 1 Ord.": "7.574", "University": "Universidad Complutense de Madrid"},
    {"Código": "0119", "TITULACIONES DE GRADO": "Publicidad y Relaciones Públicas", "Grupo 1 Ord.": "10.833", "University": "Universidad Complutense de Madrid"},
    {"Código": "0120", "TITULACIONES DE GRADO": "Relaciones Internacionales", "Grupo 1 Ord.": "11.878", "University": "Universidad Complutense de Madrid"},
    {"Código": "0121", "TITULACIONES DE GRADO": "Relaciones Laborales y Recursos Humanos", "Grupo 1 Ord.": "8.086", "University": "Universidad Complutense de Madrid"},
    {"Código": "0122", "TITULACIONES DE GRADO": "Sociología", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0123", "TITULACIONES DE GRADO": "Trabajo Social", "Grupo 1 Ord.": "7.593", "University": "Universidad Complutense de Madrid"},
    {"Código": "0124", "TITULACIONES DE GRADO": "Turismo", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"}
]

df_social_sciences_law5 = pd.DataFrame(data_social_sciences_law5)

df_social_sciences_law5

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0100,Administración y Dirección de Empresas,10.385,Universidad Complutense de Madrid
1,0128,Administración y Dirección de Empresas (en ing...,11.157,Universidad Complutense de Madrid
2,0101,Antropología Social y Cultural,5.000,Universidad Complutense de Madrid
3,0125,Ciencia de los Datos Aplicada,11.304,Universidad Complutense de Madrid
4,0102,Ciencias Políticas,5.000,Universidad Complutense de Madrid
5,0103,Comercio,8.261,Universidad Complutense de Madrid
6,0104,Comunicación Audiovisual,10.486,Universidad Complutense de Madrid
7,0126,Criminología,11.599,Universidad Complutense de Madrid
8,0106,Derecho,8.875,Universidad Complutense de Madrid
9,0108,Economía,9.211,Universidad Complutense de Madrid
10,0129,Economía (en inglés),10.250,Universidad Complutense de Madrid
11,0109,Educación Social,8.399,Universidad Complutense de Madrid
12,0110,Estadística Aplicada,9.111,Universidad Complutense de Madrid
13,0127,"Finanzas, Banca y Seguros",9.828,Universidad Complutense de Madrid
14,0111,Geografía y Ordenación del Territorio,5.000,Universidad Complutense de Madrid
15,0112,Gestión y Administración Pública,5.011,Universidad Complutense de Madrid
16,0114,Información y Documentación,5.000,Universidad Complutense de Madrid
17,0115,Maestro de Educación Infantil,9.460,Universidad Complutense de Madrid
18,0116,Maestro de Educación Primaria,10.511,Universidad Complutense de Madrid
19,0117,Pedagogía,9.200,Universidad Complutense de Madrid
20,0118,Periodismo,7.574,Universidad Complutense de Madrid
21,0119,Publicidad y Relaciones Públicas,10.833,Universidad Complutense de Madrid
22,0120,Relaciones Internacionales,11.878,Universidad Complutense de Madrid
23,0121,Relaciones Laborales y Recursos Humanos,8.086,Universidad Complutense de Madrid
24,0122,Sociología,5.000,Universidad Complutense de Madrid
25,0123,Trabajo Social,7.593,Universidad Complutense de Madrid
26,0124,Turismo,5.000,Universidad Complutense de Madrid

In [50]:
data_double_degrees6 = [
    {"Código": "0130", "TITULACIONES DE GRADO": "ADE - Ingeniería Informática", "Grupo 1 Ord.": "11.689", "University": "Universidad Complutense de Madrid"},
    {"Código": "0148", "TITULACIONES DE GRADO": "Ciencias Políticas - Filosofía", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0140", "TITULACIONES DE GRADO": "Derecho - ADE", "Grupo 1 Ord.": "10.950", "University": "Universidad Complutense de Madrid"},
    {"Código": "0143", "TITULACIONES DE GRADO": "Derecho - Ciencias Políticas", "Grupo 1 Ord.": "10.329", "University": "Universidad Complutense de Madrid"},
    {"Código": "0194", "TITULACIONES DE GRADO": "Derecho - Estudios Jurídico Militares", "Grupo 1 Ord.": "9.889", "University": "Universidad Complutense de Madrid"},
    {"Código": "0145", "TITULACIONES DE GRADO": "Derecho - Filosofía", "Grupo 1 Ord.": "8.075", "University": "Universidad Complutense de Madrid"},
    {"Código": "0141", "TITULACIONES DE GRADO": "Derecho - Relaciones Laborales y Recursos Humanos", "Grupo 1 Ord.": "10.215", "University": "Universidad Complutense de Madrid"},
    {"Código": "0137", "TITULACIONES DE GRADO": "Economía - Matemáticas y Ciencia de Datos", "Grupo 1 Ord.": "12.975", "University": "Universidad Complutense de Madrid"},
    {"Código": "0134", "TITULACIONES DE GRADO": "Economía - Relaciones Internacionales", "Grupo 1 Ord.": "12.970", "University": "Universidad Complutense de Madrid"},
    {"Código": "0199", "TITULACIONES DE GRADO": "Farmacia - Nutrición Humana y Dietética", "Grupo 1 Ord.": "12.588", "University": "Universidad Complutense de Madrid"},
    {"Código": "0135", "TITULACIONES DE GRADO": "Gestión y Administración Pública - Economía", "Grupo 1 Ord.": "8.900", "University": "Universidad Complutense de Madrid"},
    {"Código": "0147", "TITULACIONES DE GRADO": "Historia - Filología Clásica", "Grupo 1 Ord.": "5.668", "University": "Universidad Complutense de Madrid"},
    {"Código": "0142", "TITULACIONES DE GRADO": "Ingeniería Informática - Matemáticas", "Grupo 1 Ord.": "13.525", "University": "Universidad Complutense de Madrid"},
    {"Código": "0131", "TITULACIONES DE GRADO": "Maestro de Ed. Infantil - Maestro de Ed. Primaria", "Grupo 1 Ord.": "11.746", "University": "Universidad Complutense de Madrid"},
    {"Código": "0132", "TITULACIONES DE GRADO": "Maestro de Educación Infantil - Pedagogía", "Grupo 1 Ord.": "9.911", "University": "Universidad Complutense de Madrid"},
    {"Código": "0133", "TITULACIONES DE GRADO": "Maestro de Educación Primaria - Pedagogía", "Grupo 1 Ord.": "11.761", "University": "Universidad Complutense de Madrid"},
    {"Código": "0144", "TITULACIONES DE GRADO": "Matemáticas - Física", "Grupo 1 Ord.": "13.736", "University": "Universidad Complutense de Madrid"},
    {"Código": "0197", "TITULACIONES DE GRADO": "Psicología - Logopedia", "Grupo 1 Ord.": "10.602", "University": "Universidad Complutense de Madrid"},
    {"Código": "0136", "TITULACIONES DE GRADO": "Química - Bioquímica", "Grupo 1 Ord.": "12.978", "University": "Universidad Complutense de Madrid"},
    {"Código": "0149", "TITULACIONES DE GRADO": "Sociología - Relaciones Internacionales", "Grupo 1 Ord.": "11.219", "University": "Universidad Complutense de Madrid"},
    {"Código": "0198", "TITULACIONES DE GRADO": "Turismo - Comercio", "Grupo 1 Ord.": "7.478", "University": "Universidad Complutense de Madrid"}
]


df_double_degrees6 = pd.DataFrame(data_double_degrees6)


df_double_degrees6

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0130,ADE - Ingeniería Informática,11.689,Universidad Complutense de Madrid
1,0148,Ciencias Políticas - Filosofía,5.000,Universidad Complutense de Madrid
2,0140,Derecho - ADE,10.950,Universidad Complutense de Madrid
3,0143,Derecho - Ciencias Políticas,10.329,Universidad Complutense de Madrid
4,0194,Derecho - Estudios Jurídico Militares,9.889,Universidad Complutense de Madrid
5,0145,Derecho - Filosofía,8.075,Universidad Complutense de Madrid
6,0141,Derecho - Relaciones Laborales y Recursos Humanos,10.215,Universidad Complutense de Madrid
7,0137,Economía - Matemáticas y Ciencia de Datos,12.975,Universidad Complutense de Madrid
8,0134,Economía - Relaciones Internacionales,12.970,Universidad Complutense de Madrid
9,0199,Farmacia - Nutrición Humana y Dietética,12.588,Universidad Complutense de Madrid
10,0135,Gestión y Administración Pública - Economía,8.900,Universidad Complutense de Madrid
11,0147,Historia - Filología Clásica,5.668,Universidad Complutense de Madrid
12,0142,Ingeniería Informática - Matemáticas,13.525,Universidad Complutense de Madrid
13,0131,Maestro de Ed. Infantil - Maestro de Ed. Primaria,11.746,Universidad Complutense de Madrid
14,0132,Maestro de Educación Infantil - Pedagogía,9.911,Universidad Complutense de Madrid
15,0133,Maestro de Educación Primaria - Pedagogía,11.761,Universidad Complutense de Madrid
16,0144,Matemáticas - Física,13.736,Universidad Complutense de Madrid
17,0197,Psicología - Logopedia,10.602,Universidad Complutense de Madrid
18,0136,Química - Bioquímica,12.978,Universidad Complutense de Madrid
19,0149,Sociología - Relaciones Internacionales,11.219,Universidad Complutense de Madrid
20,0198,Turismo - Comercio,7.478,Universidad Complutense de Madrid

In [51]:
data_interuniversity_degrees7 = [
    {"Código": "0196", "TITULACIONES DE GRADO": "Bachelor of Arts in European Studies", "Grupo 1 Ord.": "8.730", "University": "Universidad Complutense de Madrid"},
    {"Código": "0368", "TITULACIONES DE GRADO": "Diseño de Moda (UPM) y Comercio (UCM)", "Grupo 1 Ord.": "5.000", "University": "Universidad Complutense de Madrid"},
    {"Código": "0138", "TITULACIONES DE GRADO": "Titulación Internacional en ADE (UCM-HWR Berlín)", "Grupo 1 Ord.": "11.498", "University": "Universidad Complutense de Madrid"},
    {"Código": "0107", "TITULACIONES DE GRADO": "Titulación Internacional en Derecho (UCM-Sorbonne)", "Grupo 1 Ord.": "9.687", "University": "Universidad Complutense de Madrid"},
    {"Código": "0139", "TITULACIONES DE GRADO": "Titulación Internacional en Economía (UCM-Sorbonne)", "Grupo 1 Ord.": "12.161", "University": "Universidad Complutense de Madrid"}
]


df_interuniversity_degrees7 = pd.DataFrame(data_interuniversity_degrees7)

df_interuniversity_degrees7

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0196,Bachelor of Arts in European Studies,8.730,Universidad Complutense de Madrid
1,0368,Diseño de Moda (UPM) y Comercio (UCM),5.000,Universidad Complutense de Madrid
2,0138,Titulación Internacional en ADE (UCM-HWR Berlín),11.498,Universidad Complutense de Madrid
3,0107,Titulación Internacional en Derecho (UCM-Sorbo...,9.687,Universidad Complutense de Madrid
4,0139,Titulación Internacional en Economía (UCM-Sorb...,12.161,Universidad Complutense de Madrid

In [52]:
data_affiliated_centers8 = [
    {"Código": "0150", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "5.000", "Centro": "CES Cardenal Cisneros"},
    {"Código": "0151", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "5.000", "Centro": "CES Cardenal Cisneros"},
    {"Código": "0153", "TITULACIONES DE GRADO": "Derecho - ADE", "Grupo 1 Ord.": "5.000", "Centro": "CES Cardenal Cisneros"},
    {"Código": "0152", "TITULACIONES DE GRADO": "Psicología", "Grupo 1 Ord.": "5.000", "Centro": "CES Cardenal Cisneros"},
    {"Código": "0160", "TITULACIONES DE GRADO": "Educación Social", "Grupo 1 Ord.": "5.000", "Centro": "CES Don Bosco"},
    {"Código": "0161", "TITULACIONES DE GRADO": "Maestro de Educación Infantil", "Grupo 1 Ord.": "5.000", "Centro": "CES Don Bosco"},
    {"Código": "0169", "TITULACIONES DE GRADO": "Maestro de Educación Infantil - Maestro de Educación Primaria", "Grupo 1 Ord.": "5.000", "Centro": "CES Don Bosco"},
    {"Código": "0162", "TITULACIONES DE GRADO": "Maestro de Educación Primaria", "Grupo 1 Ord.": "5.000", "Centro": "CES Don Bosco"},
    {"Código": "0168", "TITULACIONES DE GRADO": "Maestro de Educación Primaria - Pedagogía", "Grupo 1 Ord.": "5.000", "Centro": "CES Don Bosco"},
    {"Código": "0163", "TITULACIONES DE GRADO": "Pedagogía", "Grupo 1 Ord.": "5.000", "Centro": "CES Don Bosco"},
    {"Código": "0180", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "5.000", "Centro": "CES IEB"},
    {"Código": "0195", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "5.000", "Centro": "ISDE"}
]


df_affiliated_centers8 = pd.DataFrame(data_affiliated_centers8)

df_affiliated_centers8

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0150,Administración y Dirección de Empresas,5.000,CES Cardenal Cisneros
1,0151,Derecho,5.000,CES Cardenal Cisneros
2,0153,Derecho - ADE,5.000,CES Cardenal Cisneros
3,0152,Psicología,5.000,CES Cardenal Cisneros
4,0160,Educación Social,5.000,CES Don Bosco
5,0161,Maestro de Educación Infantil,5.000,CES Don Bosco
6,0169,Maestro de Educación Infantil - Maestro de Edu...,5.000,CES Don Bosco
7,0162,Maestro de Educación Primaria,5.000,CES Don Bosco
8,0168,Maestro de Educación Primaria - Pedagogía,5.000,CES Don Bosco
9,0163,Pedagogía,5.000,CES Don Bosco
10,0180,Derecho,5.000,CES IEB
11,0195,Derecho,5.000,ISDE

In [53]:
data_uam_arts_humanities9 = [
    {"Código": "0218", "TITULACIONES DE GRADO": "Arqueología", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0200", "TITULACIONES DE GRADO": "Estudios Clásicos y de la Antigüedad", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0201", "TITULACIONES DE GRADO": "Estudios de Asia y África (Árabe)", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0202", "TITULACIONES DE GRADO": "Estudios de Asia y África (Chino)", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0203", "TITULACIONES DE GRADO": "Estudios de Asia y África (Japonés)", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0204", "TITULACIONES DE GRADO": "Estudios Hispánicos: Lengua Española y sus Literaturas", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0205", "TITULACIONES DE GRADO": "Estudios Ingleses", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0206", "TITULACIONES DE GRADO": "Filosofía", "Grupo 1 Ord.": "5.517", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0207", "TITULACIONES DE GRADO": "Historia", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0208", "TITULACIONES DE GRADO": "Historia del Arte", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0209", "TITULACIONES DE GRADO": "Historia y Ciencias de la Música y Tecnología Musical", "Grupo 1 Ord.": "8.460", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0210", "TITULACIONES DE GRADO": "Lenguas Modernas, Cultura y Comunicación-Español", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0211", "TITULACIONES DE GRADO": "Lenguas Modernas, Cultura y Comunicación-Francés", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0212", "TITULACIONES DE GRADO": "Lenguas Modernas, Cultura y Comunicación-Inglés", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0213", "TITULACIONES DE GRADO": "Traducción e Interpretación (Francés)", "Grupo 1 Ord.": "5.910", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0214", "TITULACIONES DE GRADO": "Traducción e Interpretación (Inglés)", "Grupo 1 Ord.": "9.561", "University": "Universidad Autónoma de Madrid"}
]


df_uam_arts_humanities9 = pd.DataFrame(data_uam_arts_humanities9)

df_uam_arts_humanities9

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0218,Arqueología,5.000,Universidad Autónoma de Madrid
1,0200,Estudios Clásicos y de la Antigüedad,5.000,Universidad Autónoma de Madrid
2,0201,Estudios de Asia y África (Árabe),5.000,Universidad Autónoma de Madrid
3,0202,Estudios de Asia y África (Chino),5.000,Universidad Autónoma de Madrid
4,0203,Estudios de Asia y África (Japonés),5.000,Universidad Autónoma de Madrid
5,0204,Estudios Hispánicos: Lengua Española y sus Lit...,5.000,Universidad Autónoma de Madrid
6,0205,Estudios Ingleses,5.000,Universidad Autónoma de Madrid
7,0206,Filosofía,5.517,Universidad Autónoma de Madrid
8,0207,Historia,5.000,Universidad Autónoma de Madrid
9,0208,Historia del Arte,5.000,Universidad Autónoma de Madrid
10,0209,Historia y Ciencias de la Música y Tecnología ...,8.460,Universidad Autónoma de Madrid
11,0210,"Lenguas Modernas, Cultura y Comunicación-Español",5.000,Universidad Autónoma de Madrid
12,0211,"Lenguas Modernas, Cultura y Comunicación-Francés",5.000,Universidad Autónoma de Madrid
13,0212,"Lenguas Modernas, Cultura y Comunicación-Inglés",5.000,Universidad Autónoma de Madrid
14,0213,Traducción e Interpretación (Francés),5.910,Universidad Autónoma de Madrid
15,0214,Traducción e Interpretación (Inglés),9.561,Universidad Autónoma de Madrid

In [54]:
data_uam_sciences_health_law10 = [
    {"Código": "0220", "TITULACIONES DE GRADO": "Biología", "Grupo 1 Ord.": "9.943", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0221", "TITULACIONES DE GRADO": "Bioquímica", "Grupo 1 Ord.": "12.318", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0223", "TITULACIONES DE GRADO": "Ciencia y Tecnología de los Alimentos", "Grupo 1 Ord.": "8.864", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0222", "TITULACIONES DE GRADO": "Ciencias Ambientales", "Grupo 1 Ord.": "7.299", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0224", "TITULACIONES DE GRADO": "Física", "Grupo 1 Ord.": "12.061", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0225", "TITULACIONES DE GRADO": "Matemáticas", "Grupo 1 Ord.": "11.988", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0226", "TITULACIONES DE GRADO": "Química", "Grupo 1 Ord.": "9.961", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0230", "TITULACIONES DE GRADO": "Enfermería (Facultad Medicina UAM)", "Grupo 1 Ord.": "11.831", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0235", "TITULACIONES DE GRADO": "Medicina", "Grupo 1 Ord.": "13.148", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0236", "TITULACIONES DE GRADO": "Nutrición Humana y Dietética", "Grupo 1 Ord.": "10.200", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0237", "TITULACIONES DE GRADO": "Psicología", "Grupo 1 Ord.": "10.739", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0260", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "10.667", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0272", "TITULACIONES DE GRADO": "Análisis de Datos en la Empresa / Business Analytics", "Grupo 1 Ord.": "11.910", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0215", "TITULACIONES DE GRADO": "Antropología Social y Cultural", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0262", "TITULACIONES DE GRADO": "Ciencias de la Actividad Física y del Deporte", "Grupo 1 Ord.": "11.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0261", "TITULACIONES DE GRADO": "Ciencia Política y Administración Pública", "Grupo 1 Ord.": "8.315", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0277", "TITULACIONES DE GRADO": "Ciencia Política y Administración Pública - Mención en Gobierno y dirección pública", "Grupo 1 Ord.": "8.980", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0278", "TITULACIONES DE GRADO": "Ciencia Política y Administración Pública - Mención en Relaciones internacionales y Unión Europea", "Grupo 1 Ord.": "12.178", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0263", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "10.226", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0273", "TITULACIONES DE GRADO": "Derecho - Mención en Derecho de la energía y del medio ambiente", "Grupo 1 Ord.": "9.137", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0274", "TITULACIONES DE GRADO": "Derecho - Mención en Derecho de los negocios internacionales", "Grupo 1 Ord.": "11.582", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0275", "TITULACIONES DE GRADO": "Derecho - Mención en Derecho digital y de las tecnologías", "Grupo 1 Ord.": "11.128", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0276", "TITULACIONES DE GRADO": "Derecho - Mención en Derechos humanos y justicia social", "Grupo 1 Ord.": "10.289", "University": "Universidad Autónoma de Madrid"}
]

df_uam_sciences_health_law10 = pd.DataFrame(data_uam_sciences_health_law10)

df_uam_sciences_health_law10

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0220,Biología,9.943,Universidad Autónoma de Madrid
1,0221,Bioquímica,12.318,Universidad Autónoma de Madrid
2,0223,Ciencia y Tecnología de los Alimentos,8.864,Universidad Autónoma de Madrid
3,0222,Ciencias Ambientales,7.299,Universidad Autónoma de Madrid
4,0224,Física,12.061,Universidad Autónoma de Madrid
5,0225,Matemáticas,11.988,Universidad Autónoma de Madrid
6,0226,Química,9.961,Universidad Autónoma de Madrid
7,0230,Enfermería (Facultad Medicina UAM),11.831,Universidad Autónoma de Madrid
8,0235,Medicina,13.148,Universidad Autónoma de Madrid
9,0236,Nutrición Humana y Dietética,10.200,Universidad Autónoma de Madrid
10,0237,Psicología,10.739,Universidad Autónoma de Madrid
11,0260,Administración y Dirección de Empresas,10.667,Universidad Autónoma de Madrid
12,0272,Análisis de Datos en la Empresa / Business Ana...,11.910,Universidad Autónoma de Madrid
13,0215,Antropología Social y Cultural,5.000,Universidad Autónoma de Madrid
14,0262,Ciencias de la Actividad Física y del Deporte,11.000,Universidad Autónoma de Madrid
15,0261,Ciencia Política y Administración Pública,8.315,Universidad Autónoma de Madrid
16,0277,Ciencia Política y Administración Pública - Me...,8.980,Universidad Autónoma de Madrid
17,0278,Ciencia Política y Administración Pública - Me...,12.178,Universidad Autónoma de Madrid
18,0263,Derecho,10.226,Universidad Autónoma de Madrid
19,0273,Derecho - Mención en Derecho de la energía y d...,9.137,Universidad Autónoma de Madrid
20,0274,Derecho - Mención en Derecho de los negocios i...,11.582,Universidad Autónoma de Madrid
21,0275,Derecho - Mención en Derecho digital y de las ...,11.128,Universidad Autónoma de Madrid
22,0276,Derecho - Mención en Derechos humanos y justic...,10.289,Universidad Autónoma de Madrid

In [55]:
data_uam_social_sciences_engineering11 = [
    {"Código": "0264", "TITULACIONES DE GRADO": "Economía", "Grupo 1 Ord.": "9.811", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0279", "TITULACIONES DE GRADO": "Economía (Grupo bilingüe: español/inglés)", "Grupo 1 Ord.": "8.889", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0265", "TITULACIONES DE GRADO": "Economía y Finanzas", "Grupo 1 Ord.": "11.423", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0216", "TITULACIONES DE GRADO": "Estudios Internacionales", "Grupo 1 Ord.": "11.410", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0266", "TITULACIONES DE GRADO": "Geografía, Geotecnologías y Sostenibilidad Territorial", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0267", "TITULACIONES DE GRADO": "Gestión Aeronáutica", "Grupo 1 Ord.": "10.864", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0268", "TITULACIONES DE GRADO": "Maestro en Educación Infantil", "Grupo 1 Ord.": "9.150", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0269", "TITULACIONES DE GRADO": "Maestro en Educación Primaria", "Grupo 1 Ord.": "10.177", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0270", "TITULACIONES DE GRADO": "Turismo", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0254", "TITULACIONES DE GRADO": "Ciencia e Ingeniería de Datos", "Grupo 1 Ord.": "11.203", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0247", "TITULACIONES DE GRADO": "Ingeniería Biomédica", "Grupo 1 Ord.": "12.611", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0252", "TITULACIONES DE GRADO": "Ingeniería de Tecnologías y Servicios de Telecomunicación", "Grupo 1 Ord.": "9.714", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0250", "TITULACIONES DE GRADO": "Ingeniería Informática", "Grupo 1 Ord.": "10.864", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0251", "TITULACIONES DE GRADO": "Ingeniería Química", "Grupo 1 Ord.": "10.545", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0253", "TITULACIONES DE GRADO": "Programa Académico en Master en Ingeniería de Telecomunicación vía Grado en Ingeniería de Tecnologías y Servicios de Telecomunicación", "Grupo 1 Ord.": "10.465", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0248", "TITULACIONES DE GRADO": "Programa Académico en Master en Ingeniería Informática vía Grado en Ingeniería Informática", "Grupo 1 Ord.": "11.650", "University": "Universidad Autónoma de Madrid"}
]

df_uam_social_sciences_engineering11 = pd.DataFrame(data_uam_social_sciences_engineering11)

df_uam_social_sciences_engineering11

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0264,Economía,9.811,Universidad Autónoma de Madrid
1,0279,Economía (Grupo bilingüe: español/inglés),8.889,Universidad Autónoma de Madrid
2,0265,Economía y Finanzas,11.423,Universidad Autónoma de Madrid
3,0216,Estudios Internacionales,11.410,Universidad Autónoma de Madrid
4,0266,"Geografía, Geotecnologías y Sostenibilidad Ter...",5.000,Universidad Autónoma de Madrid
5,0267,Gestión Aeronáutica,10.864,Universidad Autónoma de Madrid
6,0268,Maestro en Educación Infantil,9.150,Universidad Autónoma de Madrid
7,0269,Maestro en Educación Primaria,10.177,Universidad Autónoma de Madrid
8,0270,Turismo,5.000,Universidad Autónoma de Madrid
9,0254,Ciencia e Ingeniería de Datos,11.203,Universidad Autónoma de Madrid
10,0247,Ingeniería Biomédica,12.611,Universidad Autónoma de Madrid
11,0252,Ingeniería de Tecnologías y Servicios de Telec...,9.714,Universidad Autónoma de Madrid
12,0250,Ingeniería Informática,10.864,Universidad Autónoma de Madrid
13,0251,Ingeniería Química,10.545,Universidad Autónoma de Madrid
14,0253,Programa Académico en Master en Ingeniería de ...,10.465,Universidad Autónoma de Madrid
15,0248,Programa Académico en Master en Ingeniería Inf...,11.650,Universidad Autónoma de Madrid

In [56]:
data_uam_double_joint_degrees12 = [
    {"Código": "0283", "TITULACIONES DE GRADO": "Ciencias Ambientales - Geografía y Ordenación del Territorio", "Grupo 1 Ord.": "6.218", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0280", "TITULACIONES DE GRADO": "Derecho - Administración y Dirección de Empresas", "Grupo 1 Ord.": "11.475", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0281", "TITULACIONES DE GRADO": "Derecho - Ciencia Política y Administración Pública", "Grupo 1 Ord.": "8.582", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0288", "TITULACIONES DE GRADO": "Estudios Internacionales - Estudios de Asia y África (Árabe)", "Grupo 1 Ord.": "9.847", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0296", "TITULACIONES DE GRADO": "Filosofía - Historia", "Grupo 1 Ord.": "12.234", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0286", "TITULACIONES DE GRADO": "Filosofía - Historia y CC. de la Música y Tecnología Musical", "Grupo 1 Ord.": "9.220", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0297", "TITULACIONES DE GRADO": "Historia - Estudios Internacionales", "Grupo 1 Ord.": "13.104", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0284", "TITULACIONES DE GRADO": "Historia del Arte - Estudios Clásicos y de la Antigüedad", "Grupo 1 Ord.": "6.520", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0298", "TITULACIONES DE GRADO": "Historia del Arte - Historia", "Grupo 1 Ord.": "12.456", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0282", "TITULACIONES DE GRADO": "Ingeniería Informática - Matemáticas", "Grupo 1 Ord.": "13.239", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0287", "TITULACIONES DE GRADO": "Maestro en Educación Infantil - Maestro en Educación Primaria", "Grupo 1 Ord.": "10.910", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0288", "TITULACIONES DE GRADO": "Nutrición Humana y Dietética - Ciencia y Tecnología de los Alimentos", "Grupo 1 Ord.": "11.322", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0299", "TITULACIONES DE GRADO": "Traducción e Interpretación (Francés) - Lenguas Modernas, Cultura y Comunicación (Francés)", "Grupo 1 Ord.": "12.578", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0217", "TITULACIONES DE GRADO": "Ciencia, Tecnología y Humanidades (UAB, UAM y UC3M)", "Grupo 1 Ord.": "5.000", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0227", "TITULACIONES DE GRADO": "Ciencias (UAB, UAM y UC3M)", "Grupo 1 Ord.": "8.050", "University": "Universidad Autónoma de Madrid"},
    {"Código": "0285", "TITULACIONES DE GRADO": "Filosofía, Política y Economía (UAB, UAM, UC3M y UPF)", "Grupo 1 Ord.": "12.222", "University": "Universidad Autónoma de Madrid"}
]

df_uam_double_joint_degrees12 = pd.DataFrame(data_uam_double_joint_degrees12)

df_uam_double_joint_degrees12

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0283,Ciencias Ambientales - Geografía y Ordenación ...,6.218,Universidad Autónoma de Madrid
1,0280,Derecho - Administración y Dirección de Empresas,11.475,Universidad Autónoma de Madrid
2,0281,Derecho - Ciencia Política y Administración Pú...,8.582,Universidad Autónoma de Madrid
3,0288,Estudios Internacionales - Estudios de Asia y ...,9.847,Universidad Autónoma de Madrid
4,0296,Filosofía - Historia,12.234,Universidad Autónoma de Madrid
5,0286,Filosofía - Historia y CC. de la Música y Tecn...,9.220,Universidad Autónoma de Madrid
6,0297,Historia - Estudios Internacionales,13.104,Universidad Autónoma de Madrid
7,0284,Historia del Arte - Estudios Clásicos y de la ...,6.520,Universidad Autónoma de Madrid
8,0298,Historia del Arte - Historia,12.456,Universidad Autónoma de Madrid
9,0282,Ingeniería Informática - Matemáticas,13.239,Universidad Autónoma de Madrid
10,0287,Maestro en Educación Infantil - Maestro en Edu...,10.910,Universidad Autónoma de Madrid
11,0288,Nutrición Humana y Dietética - Ciencia y Tecno...,11.322,Universidad Autónoma de Madrid
12,0299,Traducción e Interpretación (Francés) - Lengua...,12.578,Universidad Autónoma de Madrid
13,0217,"Ciencia, Tecnología y Humanidades (UAB, UAM y ...",5.000,Universidad Autónoma de Madrid
14,0227,"Ciencias (UAB, UAM y UC3M)",8.050,Universidad Autónoma de Madrid
15,0285,"Filosofía, Política y Economía (UAB, UAM, UC3M...",12.222,Universidad Autónoma de Madrid

In [57]:
data_uam_affiliated_centers13 = [
    {"Código": "0271", "TITULACIONES DE GRADO": "Diseño y Gestión de Proyectos Transmedia", "Grupo 1 Ord.": "5.000", "Centro": "CES Universitario La Salle"},
    {"Código": "0290", "TITULACIONES DE GRADO": "Educación Social", "Grupo 1 Ord.": "5.000", "Centro": "CES Universitario La Salle"},
    {"Código": "0291", "TITULACIONES DE GRADO": "Fisioterapia", "Grupo 1 Ord.": "5.000", "Centro": "CES Universitario La Salle"},
    {"Código": "0292", "TITULACIONES DE GRADO": "Maestro en Educación Infantil", "Grupo 1 Ord.": "5.000", "Centro": "CES Universitario La Salle"},
    {"Código": "0293", "TITULACIONES DE GRADO": "Maestro en Educación Primaria", "Grupo 1 Ord.": "5.000", "Centro": "CES Universitario La Salle"},
    {"Código": "0238", "TITULACIONES DE GRADO": "Podología", "Grupo 1 Ord.": "6.430", "Centro": "CES Universitario La Salle"},
    {"Código": "0294", "TITULACIONES DE GRADO": "Terapia Ocupacional", "Grupo 1 Ord.": "5.000", "Centro": "CES Universitario La Salle"},
    {"Código": "0295", "TITULACIONES DE GRADO": "Trabajo Social", "Grupo 1 Ord.": "5.000", "Centro": "CES Universitario La Salle"},
    {"Código": "0233", "TITULACIONES DE GRADO": "Enfermería", "Grupo 1 Ord.": "10.964", "Centro": "E.U. Enfermería Cruz Roja"},
    {"Código": "0234", "TITULACIONES DE GRADO": "Enfermería", "Grupo 1 Ord.": "10.777", "Centro": "E.U. Enfermería Fundación Jiménez Díaz"},
    {"Código": "0231", "TITULACIONES DE GRADO": "Enfermería (Campus Villalba)", "Grupo 1 Ord.": "10.683", "Centro": "E.U. Enfermería Fundación Jiménez Díaz"}
]


df_uam_affiliated_centers13 = pd.DataFrame(data_uam_affiliated_centers13)

df_uam_affiliated_centers13

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0271,Diseño y Gestión de Proyectos Transmedia,5.000,CES Universitario La Salle
1,0290,Educación Social,5.000,CES Universitario La Salle
2,0291,Fisioterapia,5.000,CES Universitario La Salle
3,0292,Maestro en Educación Infantil,5.000,CES Universitario La Salle
4,0293,Maestro en Educación Primaria,5.000,CES Universitario La Salle
5,0238,Podología,6.430,CES Universitario La Salle
6,0294,Terapia Ocupacional,5.000,CES Universitario La Salle
7,0295,Trabajo Social,5.000,CES Universitario La Salle
8,0233,Enfermería,10.964,E.U. Enfermería Cruz Roja
9,0234,Enfermería,10.777,E.U. Enfermería Fundación Jiménez Díaz
10,0231,Enfermería (Campus Villalba),10.683,E.U. Enfermería Fundación Jiménez Díaz

In [58]:
data_ua_arts_sciences_health14 = [
    {"Código": "0400", "TITULACIONES DE GRADO": "Estudios Hispánicos", "Grupo 1 Ord.": "5.000", "University": "Universidad de Alcalá"},
    {"Código": "0401", "TITULACIONES DE GRADO": "Estudios Ingleses", "Grupo 1 Ord.": "7.020", "University": "Universidad de Alcalá"},
    {"Código": "0402", "TITULACIONES DE GRADO": "Historia", "Grupo 1 Ord.": "5.000", "University": "Universidad de Alcalá"},
    {"Código": "0403", "TITULACIONES DE GRADO": "Humanidades", "Grupo 1 Ord.": "5.000", "University": "Universidad de Alcalá"},
    {"Código": "0404", "TITULACIONES DE GRADO": "Lenguas Modernas y Traducción", "Grupo 1 Ord.": "6.386", "University": "Universidad de Alcalá"},
    {"Código": "0405", "TITULACIONES DE GRADO": "Lenguas Modernas y Traducción (Guadalajara)", "Grupo 1 Ord.": "5.000", "University": "Universidad de Alcalá"},
    {"Código": "0410", "TITULACIONES DE GRADO": "Biología", "Grupo 1 Ord.": "10.925", "University": "Universidad de Alcalá"},
    {"Código": "0411", "TITULACIONES DE GRADO": "Ciencias Ambientales", "Grupo 1 Ord.": "5.489", "University": "Universidad de Alcalá"},
    {"Código": "0413", "TITULACIONES DE GRADO": "Criminalística: Ciencias y Tecnologías Forenses", "Grupo 1 Ord.": "12.374", "University": "Universidad de Alcalá"},
    {"Código": "0415", "TITULACIONES DE GRADO": "Física e Instrumentación Espacial", "Grupo 1 Ord.": "12.025", "University": "Universidad de Alcalá"},
    {"Código": "0412", "TITULACIONES DE GRADO": "Química", "Grupo 1 Ord.": "10.285", "University": "Universidad de Alcalá"},
    {"Código": "0420", "TITULACIONES DE GRADO": "Biología Sanitaria", "Grupo 1 Ord.": "12.500", "University": "Universidad de Alcalá"},
    {"Código": "0421", "TITULACIONES DE GRADO": "Ciencias de la Actividad Física y del Deporte", "Grupo 1 Ord.": "10.890", "University": "Universidad de Alcalá"},
    {"Código": "0422", "TITULACIONES DE GRADO": "Enfermería", "Grupo 1 Ord.": "11.760", "University": "Universidad de Alcalá"},
    {"Código": "0423", "TITULACIONES DE GRADO": "Enfermería (Guadalajara)", "Grupo 1 Ord.": "11.614", "University": "Universidad de Alcalá"},
    {"Código": "0424", "TITULACIONES DE GRADO": "Farmacia", "Grupo 1 Ord.": "11.610", "University": "Universidad de Alcalá"},
    {"Código": "0425", "TITULACIONES DE GRADO": "Fisioterapia", "Grupo 1 Ord.": "11.425", "University": "Universidad de Alcalá"},
    {"Código": "0426", "TITULACIONES DE GRADO": "Medicina", "Grupo 1 Ord.": "13.102", "University": "Universidad de Alcalá"}
]


df_ua_arts_sciences_health14 = pd.DataFrame(data_ua_arts_sciences_health14)

df_ua_arts_sciences_health14

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0400,Estudios Hispánicos,5.000,Universidad de Alcalá
1,0401,Estudios Ingleses,7.020,Universidad de Alcalá
2,0402,Historia,5.000,Universidad de Alcalá
3,0403,Humanidades,5.000,Universidad de Alcalá
4,0404,Lenguas Modernas y Traducción,6.386,Universidad de Alcalá
5,0405,Lenguas Modernas y Traducción (Guadalajara),5.000,Universidad de Alcalá
6,0410,Biología,10.925,Universidad de Alcalá
7,0411,Ciencias Ambientales,5.489,Universidad de Alcalá
8,0413,Criminalística: Ciencias y Tecnologías Forenses,12.374,Universidad de Alcalá
9,0415,Física e Instrumentación Espacial,12.025,Universidad de Alcalá
10,0412,Química,10.285,Universidad de Alcalá
11,0420,Biología Sanitaria,12.500,Universidad de Alcalá
12,0421,Ciencias de la Actividad Física y del Deporte,10.890,Universidad de Alcalá
13,0422,Enfermería,11.760,Universidad de Alcalá
14,0423,Enfermería (Guadalajara),11.614,Universidad de Alcalá
15,0424,Farmacia,11.610,Universidad de Alcalá
16,0425,Fisioterapia,11.425,Universidad de Alcalá
17,0426,Medicina,13.102,Universidad de Alcalá

In [59]:
data_ua_social_sciences_engineering15 = [
    {"Código": "0460", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "10.311", "University": "Universidad de Alcalá"},
    {"Código": "0461", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (Guadalajara)", "Grupo 1 Ord.": "8.842", "University": "Universidad de Alcalá"},
    {"Código": "0462", "TITULACIONES DE GRADO": "Comunicación Audiovisual (Guadalajara)", "Grupo 1 Ord.": "8.959", "University": "Universidad de Alcalá"},
    {"Código": "0463", "TITULACIONES DE GRADO": "Finanzas", "Grupo 1 Ord.": "8.600", "University": "Universidad de Alcalá"},
    {"Código": "0464", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "8.865", "University": "Universidad de Alcalá"},
    {"Código": "0465", "TITULACIONES DE GRADO": "Economía", "Grupo 1 Ord.": "8.902", "University": "Universidad de Alcalá"},
    {"Código": "0466", "TITULACIONES DE GRADO": "Economía y Negocios Internacionales", "Grupo 1 Ord.": "11.918", "University": "Universidad de Alcalá"},
    {"Código": "0471", "TITULACIONES DE GRADO": "Economía y Negocios Internacionales (docencia en inglés)", "Grupo 1 Ord.": "10.814", "University": "Universidad de Alcalá"},
    {"Código": "0468", "TITULACIONES DE GRADO": "Magisterio de Educación Infantil (Guadalajara)", "Grupo 1 Ord.": "8.753", "University": "Universidad de Alcalá"},
    {"Código": "0467", "TITULACIONES DE GRADO": "Magisterio de Educación Primaria (bilingüe) (docencia en inglés) (Guadalajara)", "Grupo 1 Ord.": "8.591", "University": "Universidad de Alcalá"},
    {"Código": "0469", "TITULACIONES DE GRADO": "Magisterio de Educación Primaria (Guadalajara)", "Grupo 1 Ord.": "9.528", "University": "Universidad de Alcalá"},
    {"Código": "0470", "TITULACIONES DE GRADO": "Turismo (Guadalajara)", "Grupo 1 Ord.": "5.000", "University": "Universidad de Alcalá"},
    {"Código": "0442", "TITULACIONES DE GRADO": "Arquitectura Técnica y Edificación (Guadalajara)", "Grupo 1 Ord.": "8.464", "University": "Universidad de Alcalá"},
    {"Código": "0440", "TITULACIONES DE GRADO": "Fundamentos de Arquitectura y Urbanismo", "Grupo 1 Ord.": "10.725", "University": "Universidad de Alcalá"},
    {"Código": "0441", "TITULACIONES DE GRADO": "Ingeniería de Computadores", "Grupo 1 Ord.": "9.186", "University": "Universidad de Alcalá"},
    {"Código": "0444", "TITULACIONES DE GRADO": "Ingeniería Electrónica de Comunicaciones", "Grupo 1 Ord.": "8.070", "University": "Universidad de Alcalá"},
    {"Código": "0443", "TITULACIONES DE GRADO": "Ingeniería Electrónica y Automática Industrial", "Grupo 1 Ord.": "10.186", "University": "Universidad de Alcalá"},
    {"Código": "0449", "TITULACIONES DE GRADO": "Ingeniería en Sistemas de Información", "Grupo 1 Ord.": "8.900", "University": "Universidad de Alcalá"},
    {"Código": "0451", "TITULACIONES DE GRADO": "Ingeniería en Sistemas de Telecomunicación", "Grupo 1 Ord.": "8.271", "University": "Universidad de Alcalá"},
    {"Código": "0450", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías de Telecomunicación", "Grupo 1 Ord.": "7.930", "University": "Universidad de Alcalá"},
    {"Código": "0446", "TITULACIONES DE GRADO": "Ingeniería de Telecomunicaciones", "Grupo 1 Ord.": "10.075", "University": "Universidad de Alcalá"},
    {"Código": "0452", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías Industriales", "Grupo 1 Ord.": "10.613", "University": "Universidad de Alcalá"},
    {"Código": "0453", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías Industriales + Master Universitario en Ingeniería Industrial", "Grupo 1 Ord.": "11.539", "University": "Universidad de Alcalá"},
    {"Código": "0454", "TITULACIONES DE GRADO": "Ingeniería Informática", "Grupo 1 Ord.": "10.886", "University": "Universidad de Alcalá"},
    {"Código": "0448", "TITULACIONES DE GRADO": "Ingeniería Telemática", "Grupo 1 Ord.": "8.014", "University": "Universidad de Alcalá"},
    {"Código": "0439", "TITULACIONES DE GRADO": "Matemáticas y Computación (Guadalajara)", "Grupo 1 Ord.": "11.349", "University": "Universidad de Alcalá"}
]


df_ua_social_sciences_engineering15 = pd.DataFrame(data_ua_social_sciences_engineering15)

df_ua_social_sciences_engineering15

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University
0,0460,Administración y Dirección de Empresas,10.311,Universidad de Alcalá
1,0461,Administración y Dirección de Empresas (Guadal...,8.842,Universidad de Alcalá
2,0462,Comunicación Audiovisual (Guadalajara),8.959,Universidad de Alcalá
3,0463,Finanzas,8.600,Universidad de Alcalá
4,0464,Derecho,8.865,Universidad de Alcalá
5,0465,Economía,8.902,Universidad de Alcalá
6,0466,Economía y Negocios Internacionales,11.918,Universidad de Alcalá
7,0471,Economía y Negocios Internacionales (docencia ...,10.814,Universidad de Alcalá
8,0468,Magisterio de Educación Infantil (Guadalajara),8.753,Universidad de Alcalá
9,0467,Magisterio de Educación Primaria (bilingüe) (d...,8.591,Universidad de Alcalá
10,0469,Magisterio de Educación Primaria (Guadalajara),9.528,Universidad de Alcalá
11,0470,Turismo (Guadalajara),5.000,Universidad de Alcalá
12,0442,Arquitectura Técnica y Edificación (Guadalajara),8.464,Universidad de Alcalá
13,0440,Fundamentos de Arquitectura y Urbanismo,10.725,Universidad de Alcalá
14,0441,Ingeniería de Computadores,9.186,Universidad de Alcalá
15,0444,Ingeniería Electrónica de Comunicaciones,8.070,Universidad de Alcalá
16,0443,Ingeniería Electrónica y Automática Industrial,10.186,Universidad de Alcalá
17,0449,Ingeniería en Sistemas de Información,8.900,Universidad de Alcalá
18,0451,Ingeniería en Sistemas de Telecomunicación,8.271,Universidad de Alcalá
19,0450,Ingeniería en Tecnologías de Telecomunicación,7.930,Universidad de Alcalá
20,0446,Ingeniería de Telecomunicaciones,10.075,Universidad de Alcalá
21,0452,Ingeniería en Tecnologías Industriales,10.613,Universidad de Alcalá
22,0453,Ingeniería en Tecnologías Industriales + Maste...,11.539,Universidad de Alcalá
23,0454,Ingeniería Informática,10.886,Universidad de Alcalá
24,0448,Ingeniería Telemática,8.014,Universidad de Alcalá
25,0439,Matemáticas y Computación (Guadalajara),11.349,Universidad de Alcalá

In [60]:
data_ua_double_degrees_affiliated_centers16 = [
    {"Código": "0480", "TITULACIONES DE GRADO": "Derecho - Administración y Dirección de Empresas", "Grupo 1 Ord.": "11.011", "University": "Universidad de Alcalá"},
    {"Código": "0482", "TITULACIONES DE GRADO": "Humanidades - Magisterio en Educación Primaria", "Grupo 1 Ord.": "10.540", "University": "Universidad de Alcalá"},
    {"Código": "0484", "TITULACIONES DE GRADO": "Ingeniería Informática - Administración y Dirección de Empresas", "Grupo 1 Ord.": "11.427", "University": "Universidad de Alcalá"},
    {"Código": "0485", "TITULACIONES DE GRADO": "Ingeniería Electrónica de Comunicaciones - Ing. Electrónica y Automática Industrial", "Grupo 1 Ord.": "9.591", "University": "Universidad de Alcalá"},
    {"Código": "0483", "TITULACIONES DE GRADO": "Magisterio de Educación Infantil - Magisterio de Educación Primaria (Guadalajara)", "Grupo 1 Ord.": "10.753", "University": "Universidad de Alcalá"},
    {"Código": "0481", "TITULACIONES DE GRADO": "Turismo - Admón. y Dirección de Empresas (Guadalajara)", "Grupo 1 Ord.": "7.516", "University": "Universidad de Alcalá"},
    {"Código": "0490", "TITULACIONES DE GRADO": "Educación Social", "Grupo 1 Ord.": "5.000", "Centro": "Centro Universitario Cardenal Cisneros"},
    {"Código": "0491", "TITULACIONES DE GRADO": "Magisterio de Educación Infantil", "Grupo 1 Ord.": "5.000", "Centro": "Centro Universitario Cardenal Cisneros"},
    {"Código": "0492", "TITULACIONES DE GRADO": "Magisterio de Educación Infantil (bilingüe) (docencia en inglés)", "Grupo 1 Ord.": "5.000", "Centro": "Centro Universitario Cardenal Cisneros"},
    {"Código": "0495", "TITULACIONES DE GRADO": "Magisterio de Educación Infantil (semipresencial)", "Grupo 1 Ord.": "5.000", "Centro": "Centro Universitario Cardenal Cisneros"},
    {"Código": "0493", "TITULACIONES DE GRADO": "Magisterio de Educación Primaria", "Grupo 1 Ord.": "8.141", "Centro": "Centro Universitario Cardenal Cisneros"},
    {"Código": "0494", "TITULACIONES DE GRADO": "Magisterio de Educación Primaria (bilingüe) (docencia en inglés)", "Grupo 1 Ord.": "5.000", "Centro": "Centro Universitario Cardenal Cisneros"},
    {"Código": "0496", "TITULACIONES DE GRADO": "Magisterio de Educación Primaria (Semipresencial)", "Grupo 1 Ord.": "5.000", "Centro": "Centro Universitario Cardenal Cisneros"},
    {"Código": "0497", "TITULACIONES DE GRADO": "Psicología", "Grupo 1 Ord.": "9.814", "Centro": "Centro Universitario Cardenal Cisneros"}
]


df_ua_double_degrees_affiliated_centers16 = pd.DataFrame(data_ua_double_degrees_affiliated_centers16)


df_ua_double_degrees_affiliated_centers16['Centro'] = df_ua_double_degrees_affiliated_centers16['Centro'].combine_first(df_ua_double_degrees_affiliated_centers16['University'])


df_ua_double_degrees_affiliated_centers = df_ua_double_degrees_affiliated_centers16.drop(columns=['University'])
df_ua_double_degrees_affiliated_centers

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0480,Derecho - Administración y Dirección de Empresas,11.011,Universidad de Alcalá
1,0482,Humanidades - Magisterio en Educación Primaria,10.540,Universidad de Alcalá
2,0484,Ingeniería Informática - Administración y Dire...,11.427,Universidad de Alcalá
3,0485,Ingeniería Electrónica de Comunicaciones - Ing...,9.591,Universidad de Alcalá
4,0483,Magisterio de Educación Infantil - Magisterio ...,10.753,Universidad de Alcalá
5,0481,Turismo - Admón. y Dirección de Empresas (Guad...,7.516,Universidad de Alcalá
6,0490,Educación Social,5.000,Centro Universitario Cardenal Cisneros
7,0491,Magisterio de Educación Infantil,5.000,Centro Universitario Cardenal Cisneros
8,0492,Magisterio de Educación Infantil (bilingüe) (d...,5.000,Centro Universitario Cardenal Cisneros
9,0495,Magisterio de Educación Infantil (semipresencial),5.000,Centro Universitario Cardenal Cisneros
10,0493,Magisterio de Educación Primaria,8.141,Centro Universitario Cardenal Cisneros
11,0494,Magisterio de Educación Primaria (bilingüe) (d...,5.000,Centro Universitario Cardenal Cisneros
12,0496,Magisterio de Educación Primaria (Semipresencial),5.000,Centro Universitario Cardenal Cisneros
13,0497,Psicología,9.814,Centro Universitario Cardenal Cisneros

In [61]:
data_uc3m_arts_sciences_social17 = [
    {"Código": "0502", "TITULACIONES DE GRADO": "Estudios Culturales (bilingüe)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0500", "TITULACIONES DE GRADO": "Humanidades", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0535", "TITULACIONES DE GRADO": "Neurociencia (en inglés)", "Grupo 1 Ord.": "13.184", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0540", "TITULACIONES DE GRADO": "Administración de Empresas (español o inglés)", "Grupo 1 Ord.": "12.066", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0541", "TITULACIONES DE GRADO": "Administración de Empresas (Colmenarejo)", "Grupo 1 Ord.": "11.405", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0542", "TITULACIONES DE GRADO": "Ciencias Políticas (español o bilingüe)", "Grupo 1 Ord.": "9.860", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0543", "TITULACIONES DE GRADO": "Comunicación Audiovisual (español o bilingüe)", "Grupo 1 Ord.": "10.951", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0544", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "11.975", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0545", "TITULACIONES DE GRADO": "Derecho (Colmenarejo)", "Grupo 1 Ord.": "11.237", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0546", "TITULACIONES DE GRADO": "Economía (español o inglés)", "Grupo 1 Ord.": "11.647", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0558", "TITULACIONES DE GRADO": "Empresa y Tecnología (en inglés)", "Grupo 1 Ord.": "12.710", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0547", "TITULACIONES DE GRADO": "Estadística y Empresa", "Grupo 1 Ord.": "11.733", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0555", "TITULACIONES DE GRADO": "Estudios Internacionales (en inglés)", "Grupo 1 Ord.": "12.700", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0548", "TITULACIONES DE GRADO": "Finanzas y Contabilidad (español o inglés)", "Grupo 1 Ord.": "11.469", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0557", "TITULACIONES DE GRADO": "Gestión de la Información y Contenidos Digitales", "Grupo 1 Ord.": "10.639", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0559", "TITULACIONES DE GRADO": "Historia y Política (bilingüe)", "Grupo 1 Ord.": "9.974", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0551", "TITULACIONES DE GRADO": "Periodismo (español o bilingüe)", "Grupo 1 Ord.": "9.500", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0552", "TITULACIONES DE GRADO": "Relaciones Laborales y Empleo", "Grupo 1 Ord.": "8.889", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0553", "TITULACIONES DE GRADO": "Sociología (español o bilingüe)", "Grupo 1 Ord.": "7.466", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0554", "TITULACIONES DE GRADO": "Turismo", "Grupo 1 Ord.": "7.403", "Centro": "Universidad Carlos III de Madrid"}
]


df_uc3m_arts_sciences_social17 = pd.DataFrame(data_uc3m_arts_sciences_social17)

df_uc3m_arts_sciences_social17

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0502,Estudios Culturales (bilingüe),5.000,Universidad Carlos III de Madrid
1,0500,Humanidades,5.000,Universidad Carlos III de Madrid
2,0535,Neurociencia (en inglés),13.184,Universidad Carlos III de Madrid
3,0540,Administración de Empresas (español o inglés),12.066,Universidad Carlos III de Madrid
4,0541,Administración de Empresas (Colmenarejo),11.405,Universidad Carlos III de Madrid
5,0542,Ciencias Políticas (español o bilingüe),9.860,Universidad Carlos III de Madrid
6,0543,Comunicación Audiovisual (español o bilingüe),10.951,Universidad Carlos III de Madrid
7,0544,Derecho,11.975,Universidad Carlos III de Madrid
8,0545,Derecho (Colmenarejo),11.237,Universidad Carlos III de Madrid
9,0546,Economía (español o inglés),11.647,Universidad Carlos III de Madrid
10,0558,Empresa y Tecnología (en inglés),12.710,Universidad Carlos III de Madrid
11,0547,Estadística y Empresa,11.733,Universidad Carlos III de Madrid
12,0555,Estudios Internacionales (en inglés),12.700,Universidad Carlos III de Madrid
13,0548,Finanzas y Contabilidad (español o inglés),11.469,Universidad Carlos III de Madrid
14,0557,Gestión de la Información y Contenidos Digitales,10.639,Universidad Carlos III de Madrid
15,0559,Historia y Política (bilingüe),9.974,Universidad Carlos III de Madrid
16,0551,Periodismo (español o bilingüe),9.500,Universidad Carlos III de Madrid
17,0552,Relaciones Laborales y Empleo,8.889,Universidad Carlos III de Madrid
18,0553,Sociología (español o bilingüe),7.466,Universidad Carlos III de Madrid
19,0554,Turismo,7.403,Universidad Carlos III de Madrid

In [62]:
data_uc3m_engineering_doubles18 = [
    {"Código": "0524", "TITULACIONES DE GRADO": "Ciencia e Ingeniería de Datos (en inglés)", "Grupo 1 Ord.": "11.458", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0510", "TITULACIONES DE GRADO": "Ingeniería Aeroespacial (en inglés)", "Grupo 1 Ord.": "13.300", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0511", "TITULACIONES DE GRADO": "Ingeniería Biomédica (en inglés)", "Grupo 1 Ord.": "12.825", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0518", "TITULACIONES DE GRADO": "Ingeniería de Comunicaciones Móviles y Espaciales (español o bilingüe)", "Grupo 1 Ord.": "10.300", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0522", "TITULACIONES DE GRADO": "Ingeniería de la Energía (en inglés)", "Grupo 1 Ord.": "11.606", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0517", "TITULACIONES DE GRADO": "Ingeniería de Sonido e Imagen (español o bilingüe)", "Grupo 1 Ord.": "9.566", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0512", "TITULACIONES DE GRADO": "Ingeniería Eléctrica (español o bilingüe)", "Grupo 1 Ord.": "10.887", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0513", "TITULACIONES DE GRADO": "Ingeniería Electrónica Industrial y Automática (español o bilingüe)", "Grupo 1 Ord.": "10.839", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0520", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías de Telecomunicación (español o bilingüe)", "Grupo 1 Ord.": "10.764", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0519", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías Industriales (español o bilingüe)", "Grupo 1 Ord.": "11.891", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0525", "TITULACIONES DE GRADO": "Ingeniería Física (en inglés)", "Grupo 1 Ord.": "13.188", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0514", "TITULACIONES DE GRADO": "Ingeniería Informática (español, bilingüe o inglés)", "Grupo 1 Ord.": "10.980", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0515", "TITULACIONES DE GRADO": "Ingeniería Informática (Colmenarejo)", "Grupo 1 Ord.": "10.586", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0516", "TITULACIONES DE GRADO": "Ingeniería Mecánica (español o bilingüe)", "Grupo 1 Ord.": "11.678", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0527", "TITULACIONES DE GRADO": "Ingeniería Robótica (en inglés)", "Grupo 1 Ord.": "11.964", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0521", "TITULACIONES DE GRADO": "Ingeniería Telemática (español o bilingüe)", "Grupo 1 Ord.": "9.936", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0526", "TITULACIONES DE GRADO": "Matemática Aplicada y Computación (en inglés)", "Grupo 1 Ord.": "12.641", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0597", "TITULACIONES DE GRADO": "Programa Académico de Ingeniería Informática vía Grado en Ing. Informática (bilingüe)", "Grupo 1 Ord.": "11.839", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0598", "TITULACIONES DE GRADO": "Programa Académico de Ingeniería de Telecomunicación vía Grado en Ing. en Tecnologías de Telecomunicación (bilingüe)", "Grupo 1 Ord.": "12.450", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0599", "TITULACIONES DE GRADO": "Programa Académico de Ingeniería Industrial vía Grado en Ing. en Tecnologías Industriales (bilingüe-español)", "Grupo 1 Ord.": "13.259", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0570", "TITULACIONES DE GRADO": "Ciencias Políticas y Sociología", "Grupo 1 Ord.": "8.764", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0583", "TITULACIONES DE GRADO": "Ciencia e Ingeniería de Datos e Ingeniería en Tecnologías de Telecomunicación (bilingüe)", "Grupo 1 Ord.": "12.052", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0571", "TITULACIONES DE GRADO": "Derecho y Administración de Empresas (español o bilingüe)", "Grupo 1 Ord.": "13.036", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0572", "TITULACIONES DE GRADO": "Derecho y Administración de Empresas (Colmenarejo)", "Grupo 1 Ord.": "11.837", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0573", "TITULACIONES DE GRADO": "Derecho y Ciencias Políticas", "Grupo 1 Ord.": "11.800", "Centro": "Universidad Carlos III de Madrid"}
]


df_uc3m_engineering_doubles18 = pd.DataFrame(data_uc3m_engineering_doubles18)

df_uc3m_engineering_doubles18

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0524,Ciencia e Ingeniería de Datos (en inglés),11.458,Universidad Carlos III de Madrid
1,0510,Ingeniería Aeroespacial (en inglés),13.300,Universidad Carlos III de Madrid
2,0511,Ingeniería Biomédica (en inglés),12.825,Universidad Carlos III de Madrid
3,0518,Ingeniería de Comunicaciones Móviles y Espacia...,10.300,Universidad Carlos III de Madrid
4,0522,Ingeniería de la Energía (en inglés),11.606,Universidad Carlos III de Madrid
5,0517,Ingeniería de Sonido e Imagen (español o bilin...,9.566,Universidad Carlos III de Madrid
6,0512,Ingeniería Eléctrica (español o bilingüe),10.887,Universidad Carlos III de Madrid
7,0513,Ingeniería Electrónica Industrial y Automática...,10.839,Universidad Carlos III de Madrid
8,0520,Ingeniería en Tecnologías de Telecomunicación ...,10.764,Universidad Carlos III de Madrid
9,0519,Ingeniería en Tecnologías Industriales (españo...,11.891,Universidad Carlos III de Madrid
10,0525,Ingeniería Física (en inglés),13.188,Universidad Carlos III de Madrid
11,0514,"Ingeniería Informática (español, bilingüe o in...",10.980,Universidad Carlos III de Madrid
12,0515,Ingeniería Informática (Colmenarejo),10.586,Universidad Carlos III de Madrid
13,0516,Ingeniería Mecánica (español o bilingüe),11.678,Universidad Carlos III de Madrid
14,0527,Ingeniería Robótica (en inglés),11.964,Universidad Carlos III de Madrid
15,0521,Ingeniería Telemática (español o bilingüe),9.936,Universidad Carlos III de Madrid
16,0526,Matemática Aplicada y Computación (en inglés),12.641,Universidad Carlos III de Madrid
17,0597,Programa Académico de Ingeniería Informática v...,11.839,Universidad Carlos III de Madrid
18,0598,Programa Académico de Ingeniería de Telecomuni...,12.450,Universidad Carlos III de Madrid
19,0599,Programa Académico de Ingeniería Industrial ví...,13.259,Universidad Carlos III de Madrid
20,0570,Ciencias Políticas y Sociología,8.764,Universidad Carlos III de Madrid
21,0583,Ciencia e Ingeniería de Datos e Ingeniería en ...,12.052,Universidad Carlos III de Madrid
22,0571,Derecho y Administración de Empresas (español ...,13.036,Universidad Carlos III de Madrid
23,0572,Derecho y Administración de Empresas (Colmenar...,11.837,Universidad Carlos III de Madrid
24,0573,Derecho y Ciencias Políticas,11.800,Universidad Carlos III de Madrid

In [63]:
data_uc3m_doubles_joint_degrees19 = [
    {"Código": "0574", "TITULACIONES DE GRADO": "Derecho y Economía (español o bilingüe)", "Grupo 1 Ord.": "12.739", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0578", "TITULACIONES DE GRADO": "Estudios Internacionales y Administración de Empresas (en inglés)", "Grupo 1 Ord.": "13.363", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0579", "TITULACIONES DE GRADO": "Estudios Internacionales y Ciencias Políticas (bilingüe)", "Grupo 1 Ord.": "12.964", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0581", "TITULACIONES DE GRADO": "Estudios Internacionales y Derecho (bilingüe)", "Grupo 1 Ord.": "13.425", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0582", "TITULACIONES DE GRADO": "Estudios Internacionales y Economía (en inglés)", "Grupo 1 Ord.": "13.132", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0584", "TITULACIONES DE GRADO": "Ingeniería Física e Ingeniería en Tecnologías Industriales (bilingüe)", "Grupo 1 Ord.": "13.288", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0576", "TITULACIONES DE GRADO": "Ingeniería Informática y Administración de Empresas (Colmenarejo)", "Grupo 1 Ord.": "11.797", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0585", "TITULACIONES DE GRADO": "Ingeniería Informática y Administración de Empresas (Leganes-Getafe)", "Grupo 1 Ord.": "12.397", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0575", "TITULACIONES DE GRADO": "Periodismo y Comunicación Audiovisual (español o bilingüe)", "Grupo 1 Ord.": "11.728", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0577", "TITULACIONES DE GRADO": "Periodismo y Humanidades", "Grupo 1 Ord.": "7.999", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0591", "TITULACIONES DE GRADO": "Ciencia, Tecnología y Humanidades (UAB, UAM y UC3M)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0590", "TITULACIONES DE GRADO": "Ciencias (UAB, UAM y UC3M)", "Grupo 1 Ord.": "9.539", "Centro": "Universidad Carlos III de Madrid"},
    {"Código": "0580", "TITULACIONES DE GRADO": "Filosofía, Política y Economía (bilingüe) (UAB, UAM, UC3M y UPF)", "Grupo 1 Ord.": "12.764", "Centro": "Universidad Carlos III de Madrid"}
]

df_uc3m_doubles_joint_degrees19 = pd.DataFrame(data_uc3m_doubles_joint_degrees19)

df_uc3m_doubles_joint_degrees19

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0574,Derecho y Economía (español o bilingüe),12.739,Universidad Carlos III de Madrid
1,0578,Estudios Internacionales y Administración de E...,13.363,Universidad Carlos III de Madrid
2,0579,Estudios Internacionales y Ciencias Políticas ...,12.964,Universidad Carlos III de Madrid
3,0581,Estudios Internacionales y Derecho (bilingüe),13.425,Universidad Carlos III de Madrid
4,0582,Estudios Internacionales y Economía (en inglés),13.132,Universidad Carlos III de Madrid
5,0584,Ingeniería Física e Ingeniería en Tecnologías ...,13.288,Universidad Carlos III de Madrid
6,0576,Ingeniería Informática y Administración de Emp...,11.797,Universidad Carlos III de Madrid
7,0585,Ingeniería Informática y Administración de Emp...,12.397,Universidad Carlos III de Madrid
8,0575,Periodismo y Comunicación Audiovisual (español...,11.728,Universidad Carlos III de Madrid
9,0577,Periodismo y Humanidades,7.999,Universidad Carlos III de Madrid
10,0591,"Ciencia, Tecnología y Humanidades (UAB, UAM y ...",5.000,Universidad Carlos III de Madrid
11,0590,"Ciencias (UAB, UAM y UC3M)",9.539,Universidad Carlos III de Madrid
12,0580,"Filosofía, Política y Economía (bilingüe) (UAB...",12.764,Universidad Carlos III de Madrid

In [64]:
data_upm_sciences_socials_engineering20 = [
    {"Código": "0330", "TITULACIONES DE GRADO": "Ciencias Agrarias y Bioeconomía", "Grupo 1 Ord.": "6.053", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0345", "TITULACIONES DE GRADO": "Matemáticas", "Grupo 1 Ord.": "12.085", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0350", "TITULACIONES DE GRADO": "Ciencias de la Actividad Física y del Deporte (INEF)", "Grupo 1 Ord.": "9.439", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0381", "TITULACIONES DE GRADO": "Arquitecto/a (PARS)", "Grupo 1 Ord.": "12.900", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0325", "TITULACIONES DE GRADO": "Arquitectura Naval / Ingeniería Marítima", "Grupo 1 Ord.": "10.550", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0333", "TITULACIONES DE GRADO": "Biotecnología", "Grupo 1 Ord.": "12.925", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0343", "TITULACIONES DE GRADO": "Ciencia de Datos e Inteligencia Artificial (Campus de Montegancedo)", "Grupo 1 Ord.": "11.736", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0344", "TITULACIONES DE GRADO": "Ciencia de Datos e Inteligencia Artificial (Campus Sur)", "Grupo 1 Ord.": "12.025", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0308", "TITULACIONES DE GRADO": "Edificación", "Grupo 1 Ord.": "7.270", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0300", "TITULACIONES DE GRADO": "Fundamentos de la Arquitectura", "Grupo 1 Ord.": "11.336", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0338", "TITULACIONES DE GRADO": "Gestión y Operaciones del Transporte Aéreo", "Grupo 1 Ord.": "11.514", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0301", "TITULACIONES DE GRADO": "Ingeniería Aeroespacial", "Grupo 1 Ord.": "12.425", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0389", "TITULACIONES DE GRADO": "Ingeniero/a Aeronáutico/a (PARS)", "Grupo 1 Ord.": "13.178", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0302", "TITULACIONES DE GRADO": "Ingeniería Agrícola", "Grupo 1 Ord.": "8.978", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0378", "TITULACIONES DE GRADO": "Ingeniero/a Agrónomo/a (PARS)", "Grupo 1 Ord.": "11.203", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0303", "TITULACIONES DE GRADO": "Ingeniería Agroambiental", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0304", "TITULACIONES DE GRADO": "Ingeniería Alimentaria", "Grupo 1 Ord.": "6.255", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0334", "TITULACIONES DE GRADO": "Ingeniería Biomédica", "Grupo 1 Ord.": "12.704", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0388", "TITULACIONES DE GRADO": "Ingeniero/a Biomédico/a (PARS)", "Grupo 1 Ord.": "13.184", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0306", "TITULACIONES DE GRADO": "Ingeniería Civil y Territorial", "Grupo 1 Ord.": "9.850", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0346", "TITULACIONES DE GRADO": "Ingeniería Civil y Territorial (Retiro)", "Grupo 1 Ord.": "9.286", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0375", "TITULACIONES DE GRADO": "Ingeniero/a de Caminos, Canales y Puertos (PARS)", "Grupo 1 Ord.": "11.614", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0307", "TITULACIONES DE GRADO": "Ingeniería de Computadores", "Grupo 1 Ord.": "9.539", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0309", "TITULACIONES DE GRADO": "Ingeniería de la Energía", "Grupo 1 Ord.": "11.069", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0339", "TITULACIONES DE GRADO": "Ingeniería de las Tecnologías de la Información Geoespacial", "Grupo 1 Ord.": "6.886", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0310", "TITULACIONES DE GRADO": "Ingeniería de Materiales", "Grupo 1 Ord.": "9.136", "Centro": "Universidad Politécnica de Madrid"}
]


df_upm_sciences_socials_engineering20 = pd.DataFrame(data_upm_sciences_socials_engineering20)

df_upm_sciences_socials_engineering20

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0330,Ciencias Agrarias y Bioeconomía,6.053,Universidad Politécnica de Madrid
1,0345,Matemáticas,12.085,Universidad Politécnica de Madrid
2,0350,Ciencias de la Actividad Física y del Deporte ...,9.439,Universidad Politécnica de Madrid
3,0381,Arquitecto/a (PARS),12.900,Universidad Politécnica de Madrid
4,0325,Arquitectura Naval / Ingeniería Marítima,10.550,Universidad Politécnica de Madrid
5,0333,Biotecnología,12.925,Universidad Politécnica de Madrid
6,0343,Ciencia de Datos e Inteligencia Artificial (Ca...,11.736,Universidad Politécnica de Madrid
7,0344,Ciencia de Datos e Inteligencia Artificial (Ca...,12.025,Universidad Politécnica de Madrid
8,0308,Edificación,7.270,Universidad Politécnica de Madrid
9,0300,Fundamentos de la Arquitectura,11.336,Universidad Politécnica de Madrid
10,0338,Gestión y Operaciones del Transporte Aéreo,11.514,Universidad Politécnica de Madrid
11,0301,Ingeniería Aeroespacial,12.425,Universidad Politécnica de Madrid
12,0389,Ingeniero/a Aeronáutico/a (PARS),13.178,Universidad Politécnica de Madrid
13,0302,Ingeniería Agrícola,8.978,Universidad Politécnica de Madrid
14,0378,Ingeniero/a Agrónomo/a (PARS),11.203,Universidad Politécnica de Madrid
15,0303,Ingeniería Agroambiental,5.000,Universidad Politécnica de Madrid
16,0304,Ingeniería Alimentaria,6.255,Universidad Politécnica de Madrid
17,0334,Ingeniería Biomédica,12.704,Universidad Politécnica de Madrid
18,0388,Ingeniero/a Biomédico/a (PARS),13.184,Universidad Politécnica de Madrid
19,0306,Ingeniería Civil y Territorial,9.850,Universidad Politécnica de Madrid
20,0346,Ingeniería Civil y Territorial (Retiro),9.286,Universidad Politécnica de Madrid
21,0375,"Ingeniero/a de Caminos, Canales y Puertos (PARS)",11.614,Universidad Politécnica de Madrid
22,0307,Ingeniería de Computadores,9.539,Universidad Politécnica de Madrid
23,0309,Ingeniería de la Energía,11.069,Universidad Politécnica de Madrid
24,0339,Ingeniería de las Tecnologías de la Informació...,6.886,Universidad Politécnica de Madrid
25,0310,Ingeniería de Materiales,9.136,Universidad Politécnica de Madrid

In [65]:
additional_data_upm_engineering21 = [
    {"Código": "0385", "TITULACIONES DE GRADO": "Ingeniero/a de Materiales (PARS)", "Grupo 1 Ord.": "10.113", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0380", "TITULACIONES DE GRADO": "Ingeniero/a de Minas (PARS)", "Grupo 1 Ord.": "10.103", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0371", "TITULACIONES DE GRADO": "Ingeniero/a de Montes (PARS)", "Grupo 1 Ord.": "8.603", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0336", "TITULACIONES DE GRADO": "Ingeniería de Organización", "Grupo 1 Ord.": "12.483", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0311", "TITULACIONES DE GRADO": "Ingeniería de Sistemas de Telecomunicación", "Grupo 1 Ord.": "9.103", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0312", "TITULACIONES DE GRADO": "Ingeniería de Sonido e Imagen", "Grupo 1 Ord.": "7.726", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0313", "TITULACIONES DE GRADO": "Ingeniería de Tecnologías y Servicios de Telecomunicación", "Grupo 1 Ord.": "9.280", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0377", "TITULACIONES DE GRADO": "Ingeniero/a de Telecomunicación (PARS)", "Grupo 1 Ord.": "11.688", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0314", "TITULACIONES DE GRADO": "Ingeniería del Medio Natural", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0315", "TITULACIONES DE GRADO": "Ingeniería del Software", "Grupo 1 Ord.": "10.125", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0372", "TITULACIONES DE GRADO": "Ingeniero/a del Software (PARS)", "Grupo 1 Ord.": "11.675", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0316", "TITULACIONES DE GRADO": "Ingeniería Eléctrica", "Grupo 1 Ord.": "10.415", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0317", "TITULACIONES DE GRADO": "Ingeniería Electrónica de Comunicaciones", "Grupo 1 Ord.": "8.564", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0318", "TITULACIONES DE GRADO": "Ingeniería Electrónica Industrial y Automática", "Grupo 1 Ord.": "10.825", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0319", "TITULACIONES DE GRADO": "Ingeniería en Diseño Industrial y Desarrollo de Producto", "Grupo 1 Ord.": "12.414", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0373", "TITULACIONES DE GRADO": "Ingeniero/a Sistemas Informáticos Distribuidos y Embebidos (PARS)", "Grupo 1 Ord.": "9.114", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0320", "TITULACIONES DE GRADO": "Ingeniería en Tecnología Minera / Ing. Geológica / Ing. Mineralúrgica y Metalúrgica de las Materias Primas / Ing. en Recursos Energéticos, Combustibles y Explosivos", "Grupo 1 Ord.": "8.114", "Centro": "Universidad Politécnica de Madrid"}
]


df_additional_upm_engineering21 = pd.DataFrame(additional_data_upm_engineering21)
df_additional_upm_engineering21

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0385,Ingeniero/a de Materiales (PARS),10.113,Universidad Politécnica de Madrid
1,0380,Ingeniero/a de Minas (PARS),10.103,Universidad Politécnica de Madrid
2,0371,Ingeniero/a de Montes (PARS),8.603,Universidad Politécnica de Madrid
3,0336,Ingeniería de Organización,12.483,Universidad Politécnica de Madrid
4,0311,Ingeniería de Sistemas de Telecomunicación,9.103,Universidad Politécnica de Madrid
5,0312,Ingeniería de Sonido e Imagen,7.726,Universidad Politécnica de Madrid
6,0313,Ingeniería de Tecnologías y Servicios de Telec...,9.280,Universidad Politécnica de Madrid
7,0377,Ingeniero/a de Telecomunicación (PARS),11.688,Universidad Politécnica de Madrid
8,0314,Ingeniería del Medio Natural,5.000,Universidad Politécnica de Madrid
9,0315,Ingeniería del Software,10.125,Universidad Politécnica de Madrid
10,0372,Ingeniero/a del Software (PARS),11.675,Universidad Politécnica de Madrid
11,0316,Ingeniería Eléctrica,10.415,Universidad Politécnica de Madrid
12,0317,Ingeniería Electrónica de Comunicaciones,8.564,Universidad Politécnica de Madrid
13,0318,Ingeniería Electrónica Industrial y Automática,10.825,Universidad Politécnica de Madrid
14,0319,Ingeniería en Diseño Industrial y Desarrollo d...,12.414,Universidad Politécnica de Madrid
15,0373,Ingeniero/a Sistemas Informáticos Distribuidos...,9.114,Universidad Politécnica de Madrid
16,0320,Ingeniería en Tecnología Minera / Ing. Geológi...,8.114,Universidad Politécnica de Madrid

In [66]:
final_data_upm_engineering22 = [
    {"Código": "0347", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías Aeroespaciales", "Grupo 1 Ord.": "12.275", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0337", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías Ambientales", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0321", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías Industriales", "Grupo 1 Ord.": "11.978", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0322", "TITULACIONES DE GRADO": "Ingeniería Forestal", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0323", "TITULACIONES DE GRADO": "Ingeniería Geomática", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0386", "TITULACIONES DE GRADO": "Ingeniero/a Industrial (PARS)", "Grupo 1 Ord.": "13.328", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0324", "TITULACIONES DE GRADO": "Ingeniería Informática", "Grupo 1 Ord.": "10.311", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0376", "TITULACIONES DE GRADO": "Ingeniero/a Informática (PARS)", "Grupo 1 Ord.": "11.675", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0326", "TITULACIONES DE GRADO": "Ingeniería Mecánica", "Grupo 1 Ord.": "11.875", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0387", "TITULACIONES DE GRADO": "Ingeniero/a Naval y Oceánica (PARS)", "Grupo 1 Ord.": "11.886", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0327", "TITULACIONES DE GRADO": "Ingeniería Química (Castellana)", "Grupo 1 Ord.": "11.749", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0328", "TITULACIONES DE GRADO": "Ingeniería Química (Embajadores)", "Grupo 1 Ord.": "11.053", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0329", "TITULACIONES DE GRADO": "Ingeniería Telemática", "Grupo 1 Ord.": "8.902", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0341", "TITULACIONES DE GRADO": "Ingeniería y Sistemas de datos (Campus Moncloa)", "Grupo 1 Ord.": "11.410", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0331", "TITULACIONES DE GRADO": "Matemáticas e Informática", "Grupo 1 Ord.": "11.714", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0335", "TITULACIONES DE GRADO": "Sistemas de Información", "Grupo 1 Ord.": "9.250", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0332", "TITULACIONES DE GRADO": "Tecnologías para la Sociedad de la Información", "Grupo 1 Ord.": "8.750", "Centro": "Universidad Politécnica de Madrid"}
]

df_final_upm_engineering22 = pd.DataFrame(final_data_upm_engineering22)

df_final_upm_engineering22

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0347,Ingeniería en Tecnologías Aeroespaciales,12.275,Universidad Politécnica de Madrid
1,0337,Ingeniería en Tecnologías Ambientales,5.000,Universidad Politécnica de Madrid
2,0321,Ingeniería en Tecnologías Industriales,11.978,Universidad Politécnica de Madrid
3,0322,Ingeniería Forestal,5.000,Universidad Politécnica de Madrid
4,0323,Ingeniería Geomática,5.000,Universidad Politécnica de Madrid
5,0386,Ingeniero/a Industrial (PARS),13.328,Universidad Politécnica de Madrid
6,0324,Ingeniería Informática,10.311,Universidad Politécnica de Madrid
7,0376,Ingeniero/a Informática (PARS),11.675,Universidad Politécnica de Madrid
8,0326,Ingeniería Mecánica,11.875,Universidad Politécnica de Madrid
9,0387,Ingeniero/a Naval y Oceánica (PARS),11.886,Universidad Politécnica de Madrid
10,0327,Ingeniería Química (Castellana),11.749,Universidad Politécnica de Madrid
11,0328,Ingeniería Química (Embajadores),11.053,Universidad Politécnica de Madrid
12,0329,Ingeniería Telemática,8.902,Universidad Politécnica de Madrid
13,0341,Ingeniería y Sistemas de datos (Campus Moncloa),11.410,Universidad Politécnica de Madrid
14,0331,Matemáticas e Informática,11.714,Universidad Politécnica de Madrid
15,0335,Sistemas de Información,9.250,Universidad Politécnica de Madrid
16,0332,Tecnologías para la Sociedad de la Información,8.750,Universidad Politécnica de Madrid

In [67]:
additional_data_upm_doubles_conjuntos23 = [
    {"Código": "0361", "TITULACIONES DE GRADO": "Edificación - Administración y Dirección de Empresas", "Grupo 1 Ord.": "8.261", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0366", "TITULACIONES DE GRADO": "Ingeniería Civil y Territorial - Administración y Dirección de Empresas", "Grupo 1 Ord.": "10.900", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0362", "TITULACIONES DE GRADO": "Ingeniería Eléctrica - Ingeniería Electrónica Industrial y Automática", "Grupo 1 Ord.": "11.514", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0367", "TITULACIONES DE GRADO": "Ingeniería Electrónica de Comunicaciones - Ingeniería Telemática", "Grupo 1 Ord.": "8.872", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0360", "TITULACIONES DE GRADO": "Ingeniería en Diseño Industrial y Desarrollo de Producto - Ingeniería Mecánica", "Grupo 1 Ord.": "12.896", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0369", "TITULACIONES DE GRADO": "Ingeniería Geomática e Ingeniería de las Tecnologías de la Información Geoespacial (Campus Sur)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0365", "TITULACIONES DE GRADO": "Ingeniería Informática - Administración y Dirección de Empresas", "Grupo 1 Ord.": "11.809", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0359", "TITULACIONES DE GRADO": "Ingeniería y Sistemas de Datos e Ingeniería Telemática (Campus Sur)", "Grupo 1 Ord.": "8.628", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0368", "TITULACIONES DE GRADO": "Diseño de Moda (UPM) y Comercio (UCM)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Politécnica de Madrid"},
    {"Código": "0340", "TITULACIONES DE GRADO": "Diseño de Moda", "Grupo 1 Ord.": "5.000", "Centro": "Centro Superior de Diseño de Moda"}
]

df_additional_upm_doubles_conjuntos23 = pd.DataFrame(additional_data_upm_doubles_conjuntos23)

df_additional_upm_doubles_conjuntos23

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0361,Edificación - Administración y Dirección de Em...,8.261,Universidad Politécnica de Madrid
1,0366,Ingeniería Civil y Territorial - Administració...,10.900,Universidad Politécnica de Madrid
2,0362,Ingeniería Eléctrica - Ingeniería Electrónica ...,11.514,Universidad Politécnica de Madrid
3,0367,Ingeniería Electrónica de Comunicaciones - Ing...,8.872,Universidad Politécnica de Madrid
4,0360,Ingeniería en Diseño Industrial y Desarrollo d...,12.896,Universidad Politécnica de Madrid
5,0369,Ingeniería Geomática e Ingeniería de las Tecno...,5.000,Universidad Politécnica de Madrid
6,0365,Ingeniería Informática - Administración y Dire...,11.809,Universidad Politécnica de Madrid
7,0359,Ingeniería y Sistemas de Datos e Ingeniería Te...,8.628,Universidad Politécnica de Madrid
8,0368,Diseño de Moda (UPM) y Comercio (UCM),5.000,Universidad Politécnica de Madrid
9,0340,Diseño de Moda,5.000,Centro Superior de Diseño de Moda

In [68]:
data_urjc_arts_sciences24 = [
    {"Código": "0600", "TITULACIONES DE GRADO": "Artes Visuales y Danza (Fuenlabrada)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0802", "TITULACIONES DE GRADO": "Bellas Artes (Aranjuez)", "Grupo 1 Ord.": "9.414", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0806", "TITULACIONES DE GRADO": "Diseño Integral y Gestión de la Imagen (Aranjuez)", "Grupo 1 Ord.": "10.825", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0884", "TITULACIONES DE GRADO": "Diseño Integral y Gestión de la Imagen (Madrid)", "Grupo 1 Ord.": "11.884", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0601", "TITULACIONES DE GRADO": "Diseño y Gestión de Moda (Aranjuez)", "Grupo 1 Ord.": "10.544", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0908", "TITULACIONES DE GRADO": "Filosofía (Fuenlabrada)", "Grupo 1 Ord.": "6.417", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0720", "TITULACIONES DE GRADO": "Historia (Fuenlabrada)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0721", "TITULACIONES DE GRADO": "Lengua y Literatura Española (Fuenlabrada)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0722", "TITULACIONES DE GRADO": "Paisajismo (Fuenlabrada)", "Grupo 1 Ord.": "6.613", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0833", "TITULACIONES DE GRADO": "Traducción e Interpretación (Aranjuez)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0885", "TITULACIONES DE GRADO": "Traducción e Interpretación (Móstoles)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0610", "TITULACIONES DE GRADO": "Biología (Móstoles)", "Grupo 1 Ord.": "10.028", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0611", "TITULACIONES DE GRADO": "Ciencia y Tecnología de los Alimentos (Móstoles)", "Grupo 1 Ord.": "7.690", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0612", "TITULACIONES DE GRADO": "Ciencias Ambientales (Móstoles)", "Grupo 1 Ord.": "6.139", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0613", "TITULACIONES DE GRADO": "Ciencias Experimentales (Móstoles)", "Grupo 1 Ord.": "7.324", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0830", "TITULACIONES DE GRADO": "Matemáticas (Móstoles)", "Grupo 1 Ord.": "11.811", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0907", "TITULACIONES DE GRADO": "Nanociencia y Nanotecnología (Móstoles)", "Grupo 1 Ord.": "11.636", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0935", "TITULACIONES DE GRADO": "Recursos Hídricos (Móstoles)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"}
]


df_urjc_arts_sciences24 = pd.DataFrame(data_urjc_arts_sciences24)

df_urjc_arts_sciences24

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0600,Artes Visuales y Danza (Fuenlabrada),5.000,Universidad Rey Juan Carlos
1,0802,Bellas Artes (Aranjuez),9.414,Universidad Rey Juan Carlos
2,0806,Diseño Integral y Gestión de la Imagen (Aranjuez),10.825,Universidad Rey Juan Carlos
3,0884,Diseño Integral y Gestión de la Imagen (Madrid),11.884,Universidad Rey Juan Carlos
4,0601,Diseño y Gestión de Moda (Aranjuez),10.544,Universidad Rey Juan Carlos
5,0908,Filosofía (Fuenlabrada),6.417,Universidad Rey Juan Carlos
6,0720,Historia (Fuenlabrada),5.000,Universidad Rey Juan Carlos
7,0721,Lengua y Literatura Española (Fuenlabrada),5.000,Universidad Rey Juan Carlos
8,0722,Paisajismo (Fuenlabrada),6.613,Universidad Rey Juan Carlos
9,0833,Traducción e Interpretación (Aranjuez),5.000,Universidad Rey Juan Carlos
10,0885,Traducción e Interpretación (Móstoles),5.000,Universidad Rey Juan Carlos
11,0610,Biología (Móstoles),10.028,Universidad Rey Juan Carlos
12,0611,Ciencia y Tecnología de los Alimentos (Móstoles),7.690,Universidad Rey Juan Carlos
13,0612,Ciencias Ambientales (Móstoles),6.139,Universidad Rey Juan Carlos
14,0613,Ciencias Experimentales (Móstoles),7.324,Universidad Rey Juan Carlos
15,0830,Matemáticas (Móstoles),11.811,Universidad Rey Juan Carlos
16,0907,Nanociencia y Nanotecnología (Móstoles),11.636,Universidad Rey Juan Carlos
17,0935,Recursos Hídricos (Móstoles),5.000,Universidad Rey Juan Carlos

In [69]:
data_urjc_health_engineering25 = [
    {"Código": "0620", "TITULACIONES DE GRADO": "Enfermería (Alcorcón)", "Grupo 1 Ord.": "11.850", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0932", "TITULACIONES DE GRADO": "Farmacia (Alcorcón)", "Grupo 1 Ord.": "12.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0621", "TITULACIONES DE GRADO": "Fisioterapia (Alcorcón)", "Grupo 1 Ord.": "11.214", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0622", "TITULACIONES DE GRADO": "Medicina (Alcorcón)", "Grupo 1 Ord.": "13.082", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0623", "TITULACIONES DE GRADO": "Odontología (Alcorcón)", "Grupo 1 Ord.": "12.734", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0624", "TITULACIONES DE GRADO": "Psicología (Alcorcón)", "Grupo 1 Ord.": "10.610", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0625", "TITULACIONES DE GRADO": "Terapia Ocupacional (Alcorcón)", "Grupo 1 Ord.": "9.350", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0835", "TITULACIONES DE GRADO": "Ciencia e Ingeniería de Datos (Fuenlabrada)", "Grupo 1 Ord.": "10.539", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0886", "TITULACIONES DE GRADO": "Diseño y Desarrollo de Videojuegos (Madrid)", "Grupo 1 Ord.": "10.214", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0815", "TITULACIONES DE GRADO": "Diseño y Desarrollo de Videojuegos (Móstoles)", "Grupo 1 Ord.": "9.967", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0643", "TITULACIONES DE GRADO": "Fundamentos de la Arquitectura (Fuenlabrada)", "Grupo 1 Ord.": "10.553", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0647", "TITULACIONES DE GRADO": "Ingeniería Aeroespacial en Aeronavegación (Fuenlabrada)", "Grupo 1 Ord.": "12.054", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0933", "TITULACIONES DE GRADO": "Ingeniería Aeroespacial en Transporte y Aeropuertos (Fuenlabrada)", "Grupo 1 Ord.": "11.930", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0912", "TITULACIONES DE GRADO": "Ingeniería Aeroespacial en Vehículos Aeroespaciales (Fuenlabrada)", "Grupo 1 Ord.": "12.242", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0630", "TITULACIONES DE GRADO": "Ingeniería Ambiental (Móstoles)", "Grupo 1 Ord.": "8.315", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0834", "TITULACIONES DE GRADO": "Ingeniería Biomédica (Fuenlabrada)", "Grupo 1 Ord.": "12.511", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0913", "TITULACIONES DE GRADO": "Ingeniería Biomédica (inglés) (Fuenlabrada)", "Grupo 1 Ord.": "12.186", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0631", "TITULACIONES DE GRADO": "Ingeniería de Computadores (Móstoles)", "Grupo 1 Ord.": "9.428", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0921", "TITULACIONES DE GRADO": "Ingeniería de la Ciberseguridad (Móstoles)", "Grupo 1 Ord.": "10.853", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0633", "TITULACIONES DE GRADO": "Ingeniería de la Energía (Móstoles)", "Grupo 1 Ord.": "10.500", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0643", "TITULACIONES DE GRADO": "Ingeniería de Materiales (Móstoles)", "Grupo 1 Ord.": "9.064", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0922", "TITULACIONES DE GRADO": "Ingeniería de Robótica Software (Fuenlabrada)", "Grupo 1 Ord.": "10.436", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0646", "TITULACIONES DE GRADO": "Ingeniería de Tecnologías Industriales (Móstoles)", "Grupo 1 Ord.": "10.964", "Centro": "Universidad Rey Juan Carlos"}
]

df_urjc_health_engineering25 = pd.DataFrame(data_urjc_health_engineering25)

df_urjc_health_engineering25

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0620,Enfermería (Alcorcón),11.850,Universidad Rey Juan Carlos
1,0932,Farmacia (Alcorcón),12.000,Universidad Rey Juan Carlos
2,0621,Fisioterapia (Alcorcón),11.214,Universidad Rey Juan Carlos
3,0622,Medicina (Alcorcón),13.082,Universidad Rey Juan Carlos
4,0623,Odontología (Alcorcón),12.734,Universidad Rey Juan Carlos
5,0624,Psicología (Alcorcón),10.610,Universidad Rey Juan Carlos
6,0625,Terapia Ocupacional (Alcorcón),9.350,Universidad Rey Juan Carlos
7,0835,Ciencia e Ingeniería de Datos (Fuenlabrada),10.539,Universidad Rey Juan Carlos
8,0886,Diseño y Desarrollo de Videojuegos (Madrid),10.214,Universidad Rey Juan Carlos
9,0815,Diseño y Desarrollo de Videojuegos (Móstoles),9.967,Universidad Rey Juan Carlos
10,0643,Fundamentos de la Arquitectura (Fuenlabrada),10.553,Universidad Rey Juan Carlos
11,0647,Ingeniería Aeroespacial en Aeronavegación (Fue...,12.054,Universidad Rey Juan Carlos
12,0933,Ingeniería Aeroespacial en Transporte y Aeropu...,11.930,Universidad Rey Juan Carlos
13,0912,Ingeniería Aeroespacial en Vehículos Aeroespac...,12.242,Universidad Rey Juan Carlos
14,0630,Ingeniería Ambiental (Móstoles),8.315,Universidad Rey Juan Carlos
15,0834,Ingeniería Biomédica (Fuenlabrada),12.511,Universidad Rey Juan Carlos
16,0913,Ingeniería Biomédica (inglés) (Fuenlabrada),12.186,Universidad Rey Juan Carlos
17,0631,Ingeniería de Computadores (Móstoles),9.428,Universidad Rey Juan Carlos
18,0921,Ingeniería de la Ciberseguridad (Móstoles),10.853,Universidad Rey Juan Carlos
19,0633,Ingeniería de la Energía (Móstoles),10.500,Universidad Rey Juan Carlos
20,0643,Ingeniería de Materiales (Móstoles),9.064,Universidad Rey Juan Carlos
21,0922,Ingeniería de Robótica Software (Fuenlabrada),10.436,Universidad Rey Juan Carlos
22,0646,Ingeniería de Tecnologías Industriales (Móstoles),10.964,Universidad Rey Juan Carlos

In [70]:
final_data_urjc_engineering25 = [
    {"Código": "0632", "TITULACIONES DE GRADO": "Ingeniería del Software (Móstoles)", "Grupo 1 Ord.": "10.090", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0934", "TITULACIONES DE GRADO": "Ingeniería Electrónica Industrial y Automática (Móstoles)", "Grupo 1 Ord.": "10.164", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0648", "TITULACIONES DE GRADO": "Ingeniería en Organización Industrial (Móstoles)", "Grupo 1 Ord.": "11.225", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0645", "TITULACIONES DE GRADO": "Ingeniería en Organización Industrial (Vicálvaro)", "Grupo 1 Ord.": "11.108", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0635", "TITULACIONES DE GRADO": "Ingeniería en Sistemas Audiovisuales y Multimedia (Fuenlabrada)", "Grupo 1 Ord.": "7.650", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0636", "TITULACIONES DE GRADO": "Ingeniería en Sistemas de Telecomunicación (Fuenlabrada)", "Grupo 1 Ord.": "9.203", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0637", "TITULACIONES DE GRADO": "Ingeniería en Tecnologías de la Telecomunicación (Fuenlabrada)", "Grupo 1 Ord.": "9.587", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0638", "TITULACIONES DE GRADO": "Ingeniería en Telemática (Fuenlabrada)", "Grupo 1 Ord.": "8.914", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0639", "TITULACIONES DE GRADO": "Ingeniería Informática (Móstoles)", "Grupo 1 Ord.": "10.655", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0640", "TITULACIONES DE GRADO": "Ingeniería Informática (Vicálvaro)", "Grupo 1 Ord.": "10.278", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0914", "TITULACIONES DE GRADO": "Ingeniería Mecánica (Móstoles)", "Grupo 1 Ord.": "11.230", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0642", "TITULACIONES DE GRADO": "Ingeniería Química (Móstoles)", "Grupo 1 Ord.": "10.639", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0866", "TITULACIONES DE GRADO": "Inteligencia Artificial (Móstoles)", "Grupo 1 Ord.": "10.400", "Centro": "Universidad Rey Juan Carlos"}
]

df_final_urjc_engineering25 = pd.DataFrame(final_data_urjc_engineering25)
df_final_urjc_engineering25

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0632,Ingeniería del Software (Móstoles),10.090,Universidad Rey Juan Carlos
1,0934,Ingeniería Electrónica Industrial y Automática...,10.164,Universidad Rey Juan Carlos
2,0648,Ingeniería en Organización Industrial (Móstoles),11.225,Universidad Rey Juan Carlos
3,0645,Ingeniería en Organización Industrial (Vicálvaro),11.108,Universidad Rey Juan Carlos
4,0635,Ingeniería en Sistemas Audiovisuales y Multime...,7.650,Universidad Rey Juan Carlos
5,0636,Ingeniería en Sistemas de Telecomunicación (Fu...,9.203,Universidad Rey Juan Carlos
6,0637,Ingeniería en Tecnologías de la Telecomunicaci...,9.587,Universidad Rey Juan Carlos
7,0638,Ingeniería en Telemática (Fuenlabrada),8.914,Universidad Rey Juan Carlos
8,0639,Ingeniería Informática (Móstoles),10.655,Universidad Rey Juan Carlos
9,0640,Ingeniería Informática (Vicálvaro),10.278,Universidad Rey Juan Carlos
10,0914,Ingeniería Mecánica (Móstoles),11.230,Universidad Rey Juan Carlos
11,0642,Ingeniería Química (Móstoles),10.639,Universidad Rey Juan Carlos
12,0866,Inteligencia Artificial (Móstoles),10.400,Universidad Rey Juan Carlos

In [71]:
data_urjc_socials26 = [
    {"Código": "0660", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (Fuenlabrada)", "Grupo 1 Ord.": "9.700", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0661", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (Inglés) (Vicálvaro)", "Grupo 1 Ord.": "9.092", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0662", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (Móstoles)", "Grupo 1 Ord.": "9.414", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0663", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (Vicálvaro)", "Grupo 1 Ord.": "9.400", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0664", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas A Distancia (Vicálvaro)", "Grupo 1 Ord.": "9.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0812", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública (Fuenlabrada)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0665", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública (Vicálvaro)", "Grupo 1 Ord.": "5.865", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0813", "TITULACIONES DE GRADO": "Ciencia, Gestión e Ingeniería de Servicios (Madrid)", "Grupo 1 Ord.": "8.574", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0845", "TITULACIONES DE GRADO": "Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) (Vicálvaro)", "Grupo 1 Ord.": "8.014", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0893", "TITULACIONES DE GRADO": "Ciencias de la Actividad Física y del Deporte (Fuenlabrada)", "Grupo 1 Ord.": "11.073", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0667", "TITULACIONES DE GRADO": "Comunicación Audiovisual (Fuenlabrada)", "Grupo 1 Ord.": "9.264", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0668", "TITULACIONES DE GRADO": "Comunicación Audiovisual (Vicálvaro)", "Grupo 1 Ord.": "9.650", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0946", "TITULACIONES DE GRADO": "Comunicación Digital (Fuenlabrada)", "Grupo 1 Ord.": "9.390", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0761", "TITULACIONES DE GRADO": "Contabilidad y Finanzas (Fuenlabrada)", "Grupo 1 Ord.": "8.680", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0707", "TITULACIONES DE GRADO": "Contabilidad y Finanzas (Móstoles)", "Grupo 1 Ord.": "8.949", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0895", "TITULACIONES DE GRADO": "Contabilidad y Finanzas (A Distancia) (Vicálvaro)", "Grupo 1 Ord.": "8.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0702", "TITULACIONES DE GRADO": "Contabilidad y Finanzas (Vicálvaro)", "Grupo 1 Ord.": "9.150", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0708", "TITULACIONES DE GRADO": "Criminología (Alcorcón)", "Grupo 1 Ord.": "10.803", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0669", "TITULACIONES DE GRADO": "Criminología (Vicálvaro)", "Grupo 1 Ord.": "11.068", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0670", "TITULACIONES DE GRADO": "Derecho (Fuenlabrada)", "Grupo 1 Ord.": "10.089", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0671", "TITULACIONES DE GRADO": "Derecho (Móstoles)", "Grupo 1 Ord.": "9.434", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0672", "TITULACIONES DE GRADO": "Derecho (Vicálvaro)", "Grupo 1 Ord.": "9.378", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0673", "TITULACIONES DE GRADO": "Derecho (Semipresencial) (Vicálvaro)", "Grupo 1 Ord.": "8.270", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0898", "TITULACIONES DE GRADO": "Dirección y Gestión de Empresas en el Ámbito Digital (Vicálvaro)", "Grupo 1 Ord.": "10.711", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0674", "TITULACIONES DE GRADO": "Economía (Fuenlabrada)", "Grupo 1 Ord.": "9.200", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0849", "TITULACIONES DE GRADO": "Economía (Inglés) (Madrid)", "Grupo 1 Ord.": "5.189", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0899", "TITULACIONES DE GRADO": "Economía (Móstoles)", "Grupo 1 Ord.": "9.991", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0675", "TITULACIONES DE GRADO": "Economía (Vicálvaro)", "Grupo 1 Ord.": "9.265", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0900", "TITULACIONES DE GRADO": "Economía Financiera y Actuarial (Móstoles)", "Grupo 1 Ord.": "8.828", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0676", "TITULACIONES DE GRADO": "Economía Financiera y Actuarial (Vicálvaro)", "Grupo 1 Ord.": "9.512", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0678", "TITULACIONES DE GRADO": "Educación Infantil (Fuenlabrada)", "Grupo 1 Ord.": "9.210", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0829", "TITULACIONES DE GRADO": "Educación Infantil (Inglés) (Vicálvaro)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"}
]


df_urjc_socials26 = pd.DataFrame(data_urjc_socials26)

df_urjc_socials26

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0660,Administración y Dirección de Empresas (Fuenla...,9.700,Universidad Rey Juan Carlos
1,0661,Administración y Dirección de Empresas (Inglés...,9.092,Universidad Rey Juan Carlos
2,0662,Administración y Dirección de Empresas (Móstoles),9.414,Universidad Rey Juan Carlos
3,0663,Administración y Dirección de Empresas (Vicálv...,9.400,Universidad Rey Juan Carlos
4,0664,Administración y Dirección de Empresas A Dista...,9.000,Universidad Rey Juan Carlos
5,0812,Ciencia Política y Gestión Pública (Fuenlabrada),5.000,Universidad Rey Juan Carlos
6,0665,Ciencia Política y Gestión Pública (Vicálvaro),5.865,Universidad Rey Juan Carlos
7,0813,"Ciencia, Gestión e Ingeniería de Servicios (Ma...",8.574,Universidad Rey Juan Carlos
8,0845,"Ciencia, Gestión e Ingeniería de Servicios (Se...",8.014,Universidad Rey Juan Carlos
9,0893,Ciencias de la Actividad Física y del Deporte ...,11.073,Universidad Rey Juan Carlos
10,0667,Comunicación Audiovisual (Fuenlabrada),9.264,Universidad Rey Juan Carlos
11,0668,Comunicación Audiovisual (Vicálvaro),9.650,Universidad Rey Juan Carlos
12,0946,Comunicación Digital (Fuenlabrada),9.390,Universidad Rey Juan Carlos
13,0761,Contabilidad y Finanzas (Fuenlabrada),8.680,Universidad Rey Juan Carlos
14,0707,Contabilidad y Finanzas (Móstoles),8.949,Universidad Rey Juan Carlos
15,0895,Contabilidad y Finanzas (A Distancia) (Vicálvaro),8.000,Universidad Rey Juan Carlos
16,0702,Contabilidad y Finanzas (Vicálvaro),9.150,Universidad Rey Juan Carlos
17,0708,Criminología (Alcorcón),10.803,Universidad Rey Juan Carlos
18,0669,Criminología (Vicálvaro),11.068,Universidad Rey Juan Carlos
19,0670,Derecho (Fuenlabrada),10.089,Universidad Rey Juan Carlos
20,0671,Derecho (Móstoles),9.434,Universidad Rey Juan Carlos
21,0672,Derecho (Vicálvaro),9.378,Universidad Rey Juan Carlos
22,0673,Derecho (Semipresencial) (Vicálvaro),8.270,Universidad Rey Juan Carlos
23,0898,Dirección y Gestión de Empresas en el Ámbito D...,10.711,Universidad Rey Juan Carlos
24,0674,Economía (Fuenlabrada),9.200,Universidad Rey Juan Carlos
25,0849,Economía (Inglés) (Madrid),5.189,Universidad Rey Juan Carlos
26,0899,Economía (Móstoles),9.991,Universidad Rey Juan Carlos
27,0675,Economía (Vicálvaro),9.265,Universidad Rey Juan Carlos
28,0900,Economía Financiera y Actuarial (Móstoles),8.828,Universidad Rey Juan Carlos
29,0676,Economía Financiera y Actuarial (Vicálvaro),9.512,Universidad Rey Juan Carlos
30,0678,Educación Infantil (Fuenlabrada),9.210,Universidad Rey Juan Carlos
31,0829,Educación Infantil (Inglés) (Vicálvaro),5.000,Universidad Rey Juan Carlos

In [72]:
data_urjc_dobles_grados27 = [
    {"Código": "0872", "TITULACIONES DE GRADO": "ADE (A distancia) (Vicálvaro) - Ciencia, Gestión e Ingeniería de Servicios (Presencial) (Madrid)", "Grupo 1 Ord.": "9.304", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0871", "TITULACIONES DE GRADO": "ADE (Presencial) - Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) (Vicálvaro)", "Grupo 1 Ord.": "10.686", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0887", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas - Derecho (Fuenlabrada)", "Grupo 1 Ord.": "9.500", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0873", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas - Derecho (Madrid)", "Grupo 1 Ord.": "10.114", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0710", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas - Derecho (Móstoles)", "Grupo 1 Ord.": "9.375", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0712", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas - Derecho (Vicálvaro)", "Grupo 1 Ord.": "10.211", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0890", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas - Marketing (Vicálvaro)", "Grupo 1 Ord.": "12.486", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0856", "TITULACIONES DE GRADO": "Bellas Artes - Diseño Integral y Gestión de la Imagen (Aranjuez)", "Grupo 1 Ord.": "12.478", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0855", "TITULACIONES DE GRADO": "Bellas Artes (Presencial) (Aranjuez) - Turismo (Semipresencial) (Vicálvaro)", "Grupo 1 Ord.": "8.314", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0820", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública - Derecho (Fuenlabrada)", "Grupo 1 Ord.": "10.186", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0714", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública - Derecho (Vicálvaro)", "Grupo 1 Ord.": "9.975", "Centro": "Universidad Rey Juan Carlos"}
]


df_urjc_dobles_grados27 = pd.DataFrame(data_urjc_dobles_grados27)

df_urjc_dobles_grados27

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0872,"ADE (A distancia) (Vicálvaro) - Ciencia, Gesti...",9.304,Universidad Rey Juan Carlos
1,0871,"ADE (Presencial) - Ciencia, Gestión e Ingenier...",10.686,Universidad Rey Juan Carlos
2,0887,Administración y Dirección de Empresas - Derec...,9.500,Universidad Rey Juan Carlos
3,0873,Administración y Dirección de Empresas - Derec...,10.114,Universidad Rey Juan Carlos
4,0710,Administración y Dirección de Empresas - Derec...,9.375,Universidad Rey Juan Carlos
5,0712,Administración y Dirección de Empresas - Derec...,10.211,Universidad Rey Juan Carlos
6,0890,Administración y Dirección de Empresas - Marke...,12.486,Universidad Rey Juan Carlos
7,0856,Bellas Artes - Diseño Integral y Gestión de la...,12.478,Universidad Rey Juan Carlos
8,0855,Bellas Artes (Presencial) (Aranjuez) - Turismo...,8.314,Universidad Rey Juan Carlos
9,0820,Ciencia Política y Gestión Pública - Derecho (...,10.186,Universidad Rey Juan Carlos
10,0714,Ciencia Política y Gestión Pública - Derecho (...,9.975,Universidad Rey Juan Carlos

In [73]:
additional_data_urjc_dobles_grados28 = [
    {"Código": "0816", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública - Economía (Fuenlabrada)", "Grupo 1 Ord.": "7.900", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0739", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública - Economía (Vicálvaro)", "Grupo 1 Ord.": "9.936", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0817", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública - Periodismo (Fuenlabrada)", "Grupo 1 Ord.": "6.919", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0740", "TITULACIONES DE GRADO": "Ciencia Política y Gestión Pública - Periodismo (Vicálvaro)", "Grupo 1 Ord.": "9.994", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0868", "TITULACIONES DE GRADO": "Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) - Ingeniería en Organización Industrial (Presencial) (Vicálvaro)", "Grupo 1 Ord.": "10.500", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0874", "TITULACIONES DE GRADO": "Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) - Marketing (Presencial) (Vicálvaro)", "Grupo 1 Ord.": "10.403", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0875", "TITULACIONES DE GRADO": "Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) - Turismo (Presencial) (Vicálvaro)", "Grupo 1 Ord.": "6.164", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0894", "TITULACIONES DE GRADO": "Ciencias de la Actividad Física y del Deporte (Presencial) (Fuenlabrada) - Educación Primaria Mención Educación Física (Semipresencial) (Vicálvaro)", "Grupo 1 Ord.": "11.980", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0713", "TITULACIONES DE GRADO": "Comunicación Audiovisual - ADE (Fuenlabrada)", "Grupo 1 Ord.": "9.568", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0742", "TITULACIONES DE GRADO": "Contabilidad y Finanzas - Relaciones Laborales y RR.HH. (Vicálvaro)", "Grupo 1 Ord.": "9.800", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0743", "TITULACIONES DE GRADO": "Criminología - Derecho (Vicálvaro)", "Grupo 1 Ord.": "12.852", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0869", "TITULACIONES DE GRADO": "Criminología - Ingeniería Informática (Vicálvaro)", "Grupo 1 Ord.": "11.450", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0819", "TITULACIONES DE GRADO": "Criminología - Psicología (Alcorcón)", "Grupo 1 Ord.": "12.855", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0876", "TITULACIONES DE GRADO": "Criminología - Trabajo Social (Alcorcón)", "Grupo 1 Ord.": "12.553", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0715", "TITULACIONES DE GRADO": "Derecho - Periodismo (Vicálvaro)", "Grupo 1 Ord.": "12.075", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0821", "TITULACIONES DE GRADO": "Derecho - Relaciones Internacionales (Fuenlabrada)", "Grupo 1 Ord.": "13.554", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0944", "TITULACIONES DE GRADO": "Derecho - Relaciones Internacionales (Inglés) (Vicálvaro)", "Grupo 1 Ord.": "13.428", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0716", "TITULACIONES DE GRADO": "Derecho - Relaciones Laborales y Recursos Humanos (Vicálvaro)", "Grupo 1 Ord.": "9.653", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0877", "TITULACIONES DE GRADO": "Derecho (Semipresencial) - Relac. Internac. (Inglés) (Presencial) (Vicálvaro)", "Grupo 1 Ord.": "12.966", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0882", "TITULACIONES DE GRADO": "Diseño y Desarrollo de Videojuegos - Ing. de Computadores (Móstoles)", "Grupo 1 Ord.": "10.068", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0885", "TITULACIONES DE GRADO": "Diseño y Desarrollo de Videojuegos - Ingeniería de Datos (Móstoles)", "Grupo 1 Ord.": "11.464", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0886", "TITULACIONES DE GRADO": "Diseño y Desarrollo de Videojuegos - Diseño Integral y Gest de la Imagen (Aranjuez)", "Grupo 1 Ord.": "11.850", "Centro": "Universidad Rey Juan Carlos"}
]


df_additional_urjc_dobles_grados28 = pd.DataFrame(additional_data_urjc_dobles_grados28)
df_additional_urjc_dobles_grados28

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0816,Ciencia Política y Gestión Pública - Economía ...,7.900,Universidad Rey Juan Carlos
1,0739,Ciencia Política y Gestión Pública - Economía ...,9.936,Universidad Rey Juan Carlos
2,0817,Ciencia Política y Gestión Pública - Periodism...,6.919,Universidad Rey Juan Carlos
3,0740,Ciencia Política y Gestión Pública - Periodism...,9.994,Universidad Rey Juan Carlos
4,0868,"Ciencia, Gestión e Ingeniería de Servicios (Se...",10.500,Universidad Rey Juan Carlos
5,0874,"Ciencia, Gestión e Ingeniería de Servicios (Se...",10.403,Universidad Rey Juan Carlos
6,0875,"Ciencia, Gestión e Ingeniería de Servicios (Se...",6.164,Universidad Rey Juan Carlos
7,0894,Ciencias de la Actividad Física y del Deporte ...,11.980,Universidad Rey Juan Carlos
8,0713,Comunicación Audiovisual - ADE (Fuenlabrada),9.568,Universidad Rey Juan Carlos
9,0742,Contabilidad y Finanzas - Relaciones Laborales...,9.800,Universidad Rey Juan Carlos
10,0743,Criminología - Derecho (Vicálvaro),12.852,Universidad Rey Juan Carlos
11,0869,Criminología - Ingeniería Informática (Vicálvaro),11.450,Universidad Rey Juan Carlos
12,0819,Criminología - Psicología (Alcorcón),12.855,Universidad Rey Juan Carlos
13,0876,Criminología - Trabajo Social (Alcorcón),12.553,Universidad Rey Juan Carlos
14,0715,Derecho - Periodismo (Vicálvaro),12.075,Universidad Rey Juan Carlos
15,0821,Derecho - Relaciones Internacionales (Fuenlabr...,13.554,Universidad Rey Juan Carlos
16,0944,Derecho - Relaciones Internacionales (Inglés) ...,13.428,Universidad Rey Juan Carlos
17,0716,Derecho - Relaciones Laborales y Recursos Huma...,9.653,Universidad Rey Juan Carlos
18,0877,Derecho (Semipresencial) - Relac. Internac. (I...,12.966,Universidad Rey Juan Carlos
19,0882,Diseño y Desarrollo de Videojuegos - Ing. de C...,10.068,Universidad Rey Juan Carlos
20,0885,Diseño y Desarrollo de Videojuegos - Ingenierí...,11.464,Universidad Rey Juan Carlos
21,0886,Diseño y Desarrollo de Videojuegos - Diseño In...,11.850,Universidad Rey Juan Carlos

In [74]:
final_additional_data_urjc_dobles_grados29 = [
    {"Código": "0717", "TITULACIONES DE GRADO": "Economía - Derecho (Fuenlabrada)", "Grupo 1 Ord.": "12.086", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0903", "TITULACIONES DE GRADO": "Economía - Derecho (Móstoles)", "Grupo 1 Ord.": "11.700", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0718", "TITULACIONES DE GRADO": "Economía - Derecho (Vicálvaro)", "Grupo 1 Ord.": "12.190", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0859", "TITULACIONES DE GRADO": "Economía - Historia (Fuenlabrada)", "Grupo 1 Ord.": "10.765", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0824", "TITULACIONES DE GRADO": "Economía - Matemáticas (Móstoles)", "Grupo 1 Ord.": "12.764", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0719", "TITULACIONES DE GRADO": "Economía - Periodismo (Vicálvaro)", "Grupo 1 Ord.": "11.264", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0901", "TITULACIONES DE GRADO": "Economía Financiera y Actuarial - ADE (Móstoles)", "Grupo 1 Ord.": "11.461", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0745", "TITULACIONES DE GRADO": "Economía Financiera y Actuarial - ADE (Vicálvaro)", "Grupo 1 Ord.": "11.986", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0902", "TITULACIONES DE GRADO": "Economía Financiera y Actuarial - Economía (Móstoles)", "Grupo 1 Ord.": "10.889", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0746", "TITULACIONES DE GRADO": "Economía Financiera y Actuarial - Economía (Vicálvaro)", "Grupo 1 Ord.": "11.553", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0823", "TITULACIONES DE GRADO": "Educación Infantil - Educación Primaria (Fuenlabrada)", "Grupo 1 Ord.": "12.225", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0905", "TITULACIONES DE GRADO": "Filosofía - Ciencia Política y Gestión Pública (Fuenlabrada)", "Grupo 1 Ord.": "5.375", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0906", "TITULACIONES DE GRADO": "Filosofía - Economía (Fuenlabrada)", "Grupo 1 Ord.": "11.323", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0861", "TITULACIONES DE GRADO": "Fundamentos de la Arquitectura - Paisajismo (Fuenlabrada)", "Grupo 1 Ord.": "10.543", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0865", "TITULACIONES DE GRADO": "Historia - Turismo (Fuenlabrada)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0947", "TITULACIONES DE GRADO": "Historia (Presencial) (Fuenlabrada) - Turismo (Semipresencial) (Vicálvaro)", "Grupo 1 Ord.": "5.000", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0747", "TITULACIONES DE GRADO": "Ingeniería Ambiental - Ingeniería en Organización Industrial (Móstoles)", "Grupo 1 Ord.": "9.861", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0723", "TITULACIONES DE GRADO": "Ingeniería de la Energía - Ingeniería Ambiental (Móstoles)", "Grupo 1 Ord.": "10.214", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0748", "TITULACIONES DE GRADO": "Ingeniería de la Energía - Ingeniería en Organización Industrial (Móstoles)", "Grupo 1 Ord.": "11.207", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0724", "TITULACIONES DE GRADO": "Ingeniería de Materiales - Ingeniería de la Energía (Móstoles)", "Grupo 1 Ord.": "9.911", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0749", "TITULACIONES DE GRADO": "Ingeniería de Materiales - Ingeniería en Organización Industrial (Móstoles)", "Grupo 1 Ord.": "10.203", "Centro": "Universidad Rey Juan Carlos"}
]


df_final_additional_urjc_dobles_grados29 = pd.DataFrame(final_additional_data_urjc_dobles_grados29)
df_final_additional_urjc_dobles_grados29

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0717,Economía - Derecho (Fuenlabrada),12.086,Universidad Rey Juan Carlos
1,0903,Economía - Derecho (Móstoles),11.700,Universidad Rey Juan Carlos
2,0718,Economía - Derecho (Vicálvaro),12.190,Universidad Rey Juan Carlos
3,0859,Economía - Historia (Fuenlabrada),10.765,Universidad Rey Juan Carlos
4,0824,Economía - Matemáticas (Móstoles),12.764,Universidad Rey Juan Carlos
5,0719,Economía - Periodismo (Vicálvaro),11.264,Universidad Rey Juan Carlos
6,0901,Economía Financiera y Actuarial - ADE (Móstoles),11.461,Universidad Rey Juan Carlos
7,0745,Economía Financiera y Actuarial - ADE (Vicálvaro),11.986,Universidad Rey Juan Carlos
8,0902,Economía Financiera y Actuarial - Economía (Mó...,10.889,Universidad Rey Juan Carlos
9,0746,Economía Financiera y Actuarial - Economía (Vi...,11.553,Universidad Rey Juan Carlos
10,0823,Educación Infantil - Educación Primaria (Fuenl...,12.225,Universidad Rey Juan Carlos
11,0905,Filosofía - Ciencia Política y Gestión Pública...,5.375,Universidad Rey Juan Carlos
12,0906,Filosofía - Economía (Fuenlabrada),11.323,Universidad Rey Juan Carlos
13,0861,Fundamentos de la Arquitectura - Paisajismo (F...,10.543,Universidad Rey Juan Carlos
14,0865,Historia - Turismo (Fuenlabrada),5.000,Universidad Rey Juan Carlos
15,0947,Historia (Presencial) (Fuenlabrada) - Turismo ...,5.000,Universidad Rey Juan Carlos
16,0747,Ingeniería Ambiental - Ingeniería en Organizac...,9.861,Universidad Rey Juan Carlos
17,0723,Ingeniería de la Energía - Ingeniería Ambienta...,10.214,Universidad Rey Juan Carlos
18,0748,Ingeniería de la Energía - Ingeniería en Organ...,11.207,Universidad Rey Juan Carlos
19,0724,Ingeniería de Materiales - Ingeniería de la En...,9.911,Universidad Rey Juan Carlos
20,0749,Ingeniería de Materiales - Ingeniería en Organ...,10.203,Universidad Rey Juan Carlos

In [75]:
last_data_urjc_dobles_grados30 = [
    {"Código": "0726", "TITULACIONES DE GRADO": "Ingeniería del Software - Matemáticas (Móstoles)", "Grupo 1 Ord.": "12.800", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0779", "TITULACIONES DE GRADO": "Ingeniería en Tecnología de Telecomunicación - Ingeniería Aeroespacial en Aeronavegación (Fuenlabrada)", "Grupo 1 Ord.": "12.602", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0730", "TITULACIONES DE GRADO": "Ingeniería Informática - ADE (Móstoles)", "Grupo 1 Ord.": "11.575", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0727", "TITULACIONES DE GRADO": "Ingeniería Informática - Ingeniería de Computadores (Móstoles)", "Grupo 1 Ord.": "10.575", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0728", "TITULACIONES DE GRADO": "Ingeniería Informática - Ingeniería del Software (Móstoles)", "Grupo 1 Ord.": "11.386", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0729", "TITULACIONES DE GRADO": "Ingeniería Informática - Matemáticas (Móstoles)", "Grupo 1 Ord.": "13.148", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0870", "TITULACIONES DE GRADO": "Ingeniería Informática (Presencial) - Administración y Dirección de Empresas (A distancia) (Vicálvaro)", "Grupo 1 Ord.": "10.989", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0756", "TITULACIONES DE GRADO": "Ingeniería Química - Ingeniería en Organización Industrial (Móstoles)", "Grupo 1 Ord.": "11.233", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0732", "TITULACIONES DE GRADO": "Ingeniería Química - Ingeniería Ambiental (Móstoles)", "Grupo 1 Ord.": "10.561", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0733", "TITULACIONES DE GRADO": "Ingeniería Química - Ingeniería de la Energía (Móstoles)", "Grupo 1 Ord.": "10.949", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0725", "TITULACIONES DE GRADO": "Ingeniería Sistemas de Telecomunicación - ADE (Fuenlabrada)", "Grupo 1 Ord.": "10.975", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0915", "TITULACIONES DE GRADO": "Lengua de Signos Española y Comunidad Sorda - Terapia Ocupacional (Alcorcón)", "Grupo 1 Ord.": "10.164", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0880", "TITULACIONES DE GRADO": "Lengua de Signos Española y Comunidad Sorda - Trabajo Social (Alcorcón)", "Grupo 1 Ord.": "8.414", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0879", "TITULACIONES DE GRADO": "Lengua de Signos Española y Comunidad Sorda (Presencial) (Alcorcón) - Educación Primaria (Semipresencial) (Vicálvaro)", "Grupo 1 Ord.": "9.140", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0734", "TITULACIONES DE GRADO": "Periodismo - Comunicación Audiovisual (Fuenlabrada)", "Grupo 1 Ord.": "9.787", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0735", "TITULACIONES DE GRADO": "Periodismo - Comunicación Audiovisual (Vicálvaro)", "Grupo 1 Ord.": "10.223", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0736", "TITULACIONES DE GRADO": "Publicidad y Relaciones Públicas - ADE (Fuenlabrada)", "Grupo 1 Ord.": "11.636", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0737", "TITULACIONES DE GRADO": "Publicidad y Relaciones Públicas - Marketing (Fuenlabrada)", "Grupo 1 Ord.": "13.089", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0825", "TITULACIONES DE GRADO": "Relaciones Internacionales - Ciencia Política y Gestión Pública (Fuenlabrada)", "Grupo 1 Ord.": "12.688", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0778", "TITULACIONES DE GRADO": "Relaciones Internacionales - Economía (Fuenlabrada)", "Grupo 1 Ord.": "12.267", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0774", "TITULACIONES DE GRADO": "Relaciones Internacionales - Periodismo (Fuenlabrada)", "Grupo 1 Ord.": "12.801", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0836", "TITULACIONES DE GRADO": "Relaciones Internacionales (inglés) - Protocolo, Organización de Eventos y Comunicación Corporativa (Vicálvaro)", "Grupo 1 Ord.": "13.127", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0881", "TITULACIONES DE GRADO": "Relaciones Laborales y RR.HH - Trabajo Social (Alcorcón)", "Grupo 1 Ord.": "9.928", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0738", "TITULACIONES DE GRADO": "Turismo - Administración y Dirección de Empresas (Fuenlabrada)", "Grupo 1 Ord.": "8.261", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0739", "TITULACIONES DE GRADO": "Turismo - Administración y Dirección de Empresas (Vicálvaro)", "Grupo 1 Ord.": "8.070", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0936", "TITULACIONES DE GRADO": "Turismo - Marketing (Vicálvaro)", "Grupo 1 Ord.": "10.728", "Centro": "Universidad Rey Juan Carlos"},
    {"Código": "0948", "TITULACIONES DE GRADO": "Turismo (Semipresencial) - Marketing (Presencial) (Vicálvaro)", "Grupo 1 Ord.": "8.375", "Centro": "Universidad Rey Juan Carlos"}
]


df_last_data_urjc_dobles_grados30 = pd.DataFrame(last_data_urjc_dobles_grados30)
df_last_data_urjc_dobles_grados30

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0726,Ingeniería del Software - Matemáticas (Móstoles),12.800,Universidad Rey Juan Carlos
1,0779,Ingeniería en Tecnología de Telecomunicación -...,12.602,Universidad Rey Juan Carlos
2,0730,Ingeniería Informática - ADE (Móstoles),11.575,Universidad Rey Juan Carlos
3,0727,Ingeniería Informática - Ingeniería de Computa...,10.575,Universidad Rey Juan Carlos
4,0728,Ingeniería Informática - Ingeniería del Softwa...,11.386,Universidad Rey Juan Carlos
5,0729,Ingeniería Informática - Matemáticas (Móstoles),13.148,Universidad Rey Juan Carlos
6,0870,Ingeniería Informática (Presencial) - Administ...,10.989,Universidad Rey Juan Carlos
7,0756,Ingeniería Química - Ingeniería en Organizació...,11.233,Universidad Rey Juan Carlos
8,0732,Ingeniería Química - Ingeniería Ambiental (Mós...,10.561,Universidad Rey Juan Carlos
9,0733,Ingeniería Química - Ingeniería de la Energía ...,10.949,Universidad Rey Juan Carlos
10,0725,Ingeniería Sistemas de Telecomunicación - ADE ...,10.975,Universidad Rey Juan Carlos
11,0915,Lengua de Signos Española y Comunidad Sorda - ...,10.164,Universidad Rey Juan Carlos
12,0880,Lengua de Signos Española y Comunidad Sorda - ...,8.414,Universidad Rey Juan Carlos
13,0879,Lengua de Signos Española y Comunidad Sorda (P...,9.140,Universidad Rey Juan Carlos
14,0734,Periodismo - Comunicación Audiovisual (Fuenlab...,9.787,Universidad Rey Juan Carlos
15,0735,Periodismo - Comunicación Audiovisual (Vicálvaro),10.223,Universidad Rey Juan Carlos
16,0736,Publicidad y Relaciones Públicas - ADE (Fuenla...,11.636,Universidad Rey Juan Carlos
17,0737,Publicidad y Relaciones Públicas - Marketing (...,13.089,Universidad Rey Juan Carlos
18,0825,Relaciones Internacionales - Ciencia Política ...,12.688,Universidad Rey Juan Carlos
19,0778,Relaciones Internacionales - Economía (Fuenlab...,12.267,Universidad Rey Juan Carlos
20,0774,Relaciones Internacionales - Periodismo (Fuenl...,12.801,Universidad Rey Juan Carlos
21,0836,Relaciones Internacionales (inglés) - Protocol...,13.127,Universidad Rey Juan Carlos
22,0881,Relaciones Laborales y RR.HH - Trabajo Social ...,9.928,Universidad Rey Juan Carlos
23,0738,Turismo - Administración y Dirección de Empres...,8.261,Universidad Rey Juan Carlos
24,0739,Turismo - Administración y Dirección de Empres...,8.070,Universidad Rey Juan Carlos
25,0936,Turismo - Marketing (Vicálvaro),10.728,Universidad Rey Juan Carlos
26,0948,Turismo (Semipresencial) - Marketing (Presenci...,8.375,Universidad Rey Juan Carlos

In [76]:
data_urjc_centros_adscritos31 = [
    {"Código": "0750", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "5.000", "Centro": "CES Escuela Superior Empresarial Relaciones Públicas-ESERP"},
    {"Código": "0888", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas - Derecho", "Grupo 1 Ord.": "5.000", "Centro": "CES Escuela Superior Empresarial Relaciones Públicas-ESERP"},
    {"Código": "0795", "TITULACIONES DE GRADO": "Criminología", "Grupo 1 Ord.": "5.000", "Centro": "CES Escuela Superior Empresarial Relaciones Públicas-ESERP"},
    {"Código": "0889", "TITULACIONES DE GRADO": "Criminología - Derecho", "Grupo 1 Ord.": "5.000", "Centro": "CES Escuela Superior Empresarial Relaciones Públicas-ESERP"},
    {"Código": "0846", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "5.000", "Centro": "CES Escuela Superior Empresarial Relaciones Públicas-ESERP"},
    {"Código": "0941", "TITULACIONES DE GRADO": "Educación Infantil", "Grupo 1 Ord.": "5.000", "Centro": "CES Escuela Superior Empresarial Relaciones Públicas-ESERP"},
    {"Código": "0752", "TITULACIONES DE GRADO": "Marketing", "Grupo 1 Ord.": "5.000", "Centro": "CES Escuela Superior Empresarial Relaciones Públicas-ESERP"},
    {"Código": "0790", "TITULACIONES DE GRADO": "Artes Escénicas - Interpretación Audiovisual", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0929", "TITULACIONES DE GRADO": "Artes Escénicas e Interpretación Audiovisual (inglés)", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0792", "TITULACIONES DE GRADO": "Bellas Artes", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0793", "TITULACIONES DE GRADO": "Cinematografía", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0945", "TITULACIONES DE GRADO": "Cinematografía (inglés)", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0937", "TITULACIONES DE GRADO": "Composición Musical", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0930", "TITULACIONES DE GRADO": "Composición Musical (inglés)", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0939", "TITULACIONES DE GRADO": "Fotografía y Creación Audiovisual", "Grupo 1 Ord.": "5.000", "Centro": "Escuela Superior de Artes Escénicas y Espectáculos-TAI"},
    {"Código": "0796", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "5.000", "Centro": "CES IEB"},
    {"Código": "0839", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "5.000", "Centro": "CEDEU"},
    {"Código": "0840", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (A distancia)", "Grupo 1 Ord.": "5.000", "Centro": "CEDEU"},
    {"Código": "0841", "TITULACIONES DE GRADO": "Derecho", "Grupo 1 Ord.": "5.000", "Centro": "CEDEU"},
    {"Código": "0842", "TITULACIONES DE GRADO": "Derecho (Semipresencial)", "Grupo 1 Ord.": "5.000", "Centro": "CEDEU"},
    {"Código": "0931", "TITULACIONES DE GRADO": "Marketing", "Grupo 1 Ord.": "5.000", "Centro": "CEDEU"},
    {"Código": "0924", "TITULACIONES DE GRADO": "Protocolo, Organización de Eventos y Comunicación Corporativa", "Grupo 1 Ord.": "5.000", "Centro": "CEDEU"},
    {"Código": "0942", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas", "Grupo 1 Ord.": "5.000", "Centro": "IUNIT"},
    {"Código": "0943", "TITULACIONES DE GRADO": "Administración y Dirección de Empresas (A distancia)", "Grupo 1 Ord.": "5.000", "Centro": "IUNIT"}
]


df_centros_adscritos_urjc31 = pd.DataFrame(data_urjc_centros_adscritos31)
df_centros_adscritos_urjc31

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0750,Administración y Dirección de Empresas,5.000,CES Escuela Superior Empresarial Relaciones Pú...
1,0888,Administración y Dirección de Empresas - Derecho,5.000,CES Escuela Superior Empresarial Relaciones Pú...
2,0795,Criminología,5.000,CES Escuela Superior Empresarial Relaciones Pú...
3,0889,Criminología - Derecho,5.000,CES Escuela Superior Empresarial Relaciones Pú...
4,0846,Derecho,5.000,CES Escuela Superior Empresarial Relaciones Pú...
5,0941,Educación Infantil,5.000,CES Escuela Superior Empresarial Relaciones Pú...
6,0752,Marketing,5.000,CES Escuela Superior Empresarial Relaciones Pú...
7,0790,Artes Escénicas - Interpretación Audiovisual,5.000,Escuela Superior de Artes Escénicas y Espectác...
8,0929,Artes Escénicas e Interpretación Audiovisual (...,5.000,Escuela Superior de Artes Escénicas y Espectác...
9,0792,Bellas Artes,5.000,Escuela Superior de Artes Escénicas y Espectác...
10,0793,Cinematografía,5.000,Escuela Superior de Artes Escénicas y Espectác...
11,0945,Cinematografía (inglés),5.000,Escuela Superior de Artes Escénicas y Espectác...
12,0937,Composición Musical,5.000,Escuela Superior de Artes Escénicas y Espectác...
13,0930,Composición Musical (inglés),5.000,Escuela Superior de Artes Escénicas y Espectác...
14,0939,Fotografía y Creación Audiovisual,5.000,Escuela Superior de Artes Escénicas y Espectác...
15,0796,Administración y Dirección de Empresas,5.000,CES IEB
16,0839,Administración y Dirección de Empresas,5.000,CEDEU
17,0840,Administración y Dirección de Empresas (A dist...,5.000,CEDEU
18,0841,Derecho,5.000,CEDEU
19,0842,Derecho (Semipresencial),5.000,CEDEU
20,0931,Marketing,5.000,CEDEU
21,0924,"Protocolo, Organización de Eventos y Comunicac...",5.000,CEDEU
22,0942,Administración y Dirección de Empresas,5.000,IUNIT
23,0943,Administración y Dirección de Empresas (A dist...,5.000,IUNIT

In [77]:
variables = globals()

dataframes = {name: var for name, var in variables.items() if isinstance(var, pd.DataFrame)}
print(f"Hay {len(dataframes)} DataFrames declarados.")


print(list(dataframes.keys()))

Hay 106 DataFrames declarados.
['_', '__', '___', 'df_arts_humanities_1', '_1', 'df_sciences2', '_2', 'df_health_sciences3', '_3', 'df_engineering_architecture4', '_4', 'df_social_sciences_law5', '_5', 'df_double_degrees6', '_6', 'df_interuniversity_degrees7', '_7', 'df_affiliated_centers8', '_8', 'df_uam_arts_humanities9', '_9', 'df_uam_sciences_health_law10', '_10', 'df_uam_social_sciences_engineering11', '_11', 'df_uam_double_joint_degrees12', '_12', 'df_uam_affiliated_centers13', '_13', 'df_ua_arts_sciences_health14', '_14', 'df_ua_social_sciences_engineering15', '_15', 'df_ua_double_degrees_affiliated_centers16', 'df_ua_double_degrees_affiliated_centers', '_16', 'df_uc3m_arts_sciences_social17', '_17', 'df_uc3m_engineering_doubles18', '_18', 'df_uc3m_doubles_joint_degrees19', '_19', 'df_upm_sciences_socials_engineering20', '_20', 'df_additional_upm_engineering21', '_21', 'df_final_upm_engineering22', '_22', 'df_additional_upm_doubles_conjuntos23', '_23', 'df_urjc_arts_sciences24', '_24', 'df_urjc_health_engineering25', '_25', 'df_final_urjc_engineering25', '_26', 'df_urjc_socials26', '_27', 'df_urjc_dobles_grados27', '_28', 'df_additional_urjc_dobles_grados28', '_29', 'df_final_additional_urjc_dobles_grados29', '_30', 'df_last_data_urjc_dobles_grados30', '_31', 'df_centros_adscritos_urjc31', '_32', 'df', 'df_notas_corte_total', '_34', '_35', '_37', '_41', '_45', '_46', '_47', '_48', '_49', '_50', '_51', '_52', '_53', '_54', '_55', '_56', '_57', '_58', '_59', '_60', '_61', '_62', '_63', '_64', '_65', '_66', '_67', '_68', '_69', '_70', '_71', '_72', '_73', '_74', '_75', '_76']

In [78]:
dataframe_names = [
    'df_arts_humanities_1', 'df_sciences2', 'df_health_sciences3', 'df_engineering_architecture4',
    'df_social_sciences_law5', 'df_double_degrees6', 'df_interuniversity_degrees7', 'df_affiliated_centers8',
    'df_uam_arts_humanities9', 'df_uam_sciences_health_law10', 'df_uam_social_sciences_engineering11',
    'df_uam_double_joint_degrees12', 'df_uam_affiliated_centers13', 'df_ua_arts_sciences_health14',
    'df_ua_social_sciences_engineering15', 'df_ua_double_degrees_affiliated_centers16', 'df_uc3m_arts_sciences_social17',
    'df_uc3m_engineering_doubles18', 'df_uc3m_doubles_joint_degrees19', 'df_upm_sciences_socials_engineering20',
    'df_additional_upm_engineering21', 'df_final_upm_engineering22', 'df_additional_upm_doubles_conjuntos23',
    'df_urjc_arts_sciences24', 'df_urjc_health_engineering25', 'df_final_urjc_engineering25', 'df_urjc_socials26',
    'df_urjc_dobles_grados27', 'df_additional_urjc_dobles_grados28', 'df_final_additional_urjc_dobles_grados29',
    'df_last_data_urjc_dobles_grados30', 'df_centros_adscritos_urjc31'
]

processed_dataframes = []

for name in dataframe_names:
    df = globals().get(name)
    
    if 'Universidad' in df.columns:
        df.rename(columns={'Universidad': 'Centro'}, inplace=True)
    
    processed_dataframes.append(df)


df_notas_corte_total = pd.concat(processed_dataframes, ignore_index=True)
df_notas_corte_total

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,University,Centro
0,0001,Arqueología,5.000,Universidad Complutense de Madrid,NaN
1,0002,Bellas Artes,10.115,Universidad Complutense de Madrid,NaN
2,0019,Ciencias de las Religiones,5.000,Universidad Complutense de Madrid,NaN
3,0004,Conservación y Restauración del Patrimonio Cul...,10.100,Universidad Complutense de Madrid,NaN
4,0005,Diseño,11.818,Universidad Complutense de Madrid,NaN
...,...,...,...,...,...
567,0842,Derecho (Semipresencial),5.000,NaN,CEDEU
568,0931,Marketing,5.000,NaN,CEDEU
569,0924,"Protocolo, Organización de Eventos y Comunicac...",5.000,NaN,CEDEU
570,0942,Administración y Dirección de Empresas,5.000,NaN,IUNIT
571,0943,Administración y Dirección de Empresas (A dist...,5.000,NaN,IUNIT

In [79]:
df_notas_corte_total['Centro'] = df_notas_corte_total['Centro'].fillna(df_notas_corte_total['University'])
df_notas_corte_total.drop(columns=['University'], inplace=True)
df_notas_corte_total

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro
0,0001,Arqueología,5.000,Universidad Complutense de Madrid
1,0002,Bellas Artes,10.115,Universidad Complutense de Madrid
2,0019,Ciencias de las Religiones,5.000,Universidad Complutense de Madrid
3,0004,Conservación y Restauración del Patrimonio Cul...,10.100,Universidad Complutense de Madrid
4,0005,Diseño,11.818,Universidad Complutense de Madrid
...,...,...,...,...
567,0842,Derecho (Semipresencial),5.000,CEDEU
568,0931,Marketing,5.000,CEDEU
569,0924,"Protocolo, Organización de Eventos y Comunicac...",5.000,CEDEU
570,0942,Administración y Dirección de Empresas,5.000,IUNIT
571,0943,Administración y Dirección de Empresas (A dist...,5.000,IUNIT

In [80]:
valores_unicos = df_notas_corte_total['TITULACIONES DE GRADO'].unique()
valores_unicos

array(['Arqueología', 'Bellas Artes', 'Ciencias de las Religiones',
       'Conservación y Restauración del Patrimonio Cultural', 'Diseño',
       'Español: Lengua y Literatura', 'Estudios Ingleses',
       'Estudios Semíticos e Islámicos', 'Estudios Teatrales',
       'Filología Clásica', 'Filosofía', 'Historia', 'Historia del Arte',
       'Lenguas Modernas y sus Literaturas',
       'Lingüística y Lenguas Aplicadas',
       'Literatura General y Comparada', 'Musicología',
       'Traducción e Interpretación', 'Biología', 'Bioquímica',
       'Ciencia y Tecnología de los Alimentos', 'Física', 'Geología',
       'Matemáticas', 'Matemáticas y Ciencia de Datos', 'Química',
       'Enfermería', 'Farmacia', 'Fisioterapia', 'Logopedia', 'Medicina',
       'Nutrición Humana y Dietética', 'Odontología',
       'Óptica y Optometría', 'Podología', 'Psicología',
       'Terapia Ocupacional', 'Veterinaria', 'Desarrollo de Videojuegos',
       'Ingeniería de Computadores',
       'Ingeniería de Datos e Inteligencia Artificial',
       'Ingeniería de Materiales', 'Ingeniería del Software',
       'Ingeniería Electrónica de Comunicaciones', 'Ingeniería Geológica',
       'Ingeniería Informática', 'Ingeniería Matemática',
       'Ingeniería Química', 'Administración y Dirección de Empresas',
       'Administración y Dirección de Empresas (en inglés)',
       'Antropología Social y Cultural', 'Ciencia de los Datos Aplicada',
       'Ciencias Políticas', 'Comercio', 'Comunicación Audiovisual',
       'Criminología', 'Derecho', 'Economía', 'Economía (en inglés)',
       'Educación Social', 'Estadística Aplicada',
       'Finanzas, Banca y Seguros',
       'Geografía y Ordenación del Territorio',
       'Gestión y Administración Pública', 'Información y Documentación',
       'Maestro de Educación Infantil', 'Maestro de Educación Primaria',
       'Pedagogía', 'Periodismo', 'Publicidad y Relaciones Públicas',
       'Relaciones Internacionales',
       'Relaciones Laborales y Recursos Humanos', 'Sociología',
       'Trabajo Social', 'Turismo', 'ADE - Ingeniería Informática',
       'Ciencias Políticas - Filosofía', 'Derecho - ADE',
       'Derecho - Ciencias Políticas',
       'Derecho - Estudios Jurídico Militares', 'Derecho - Filosofía',
       'Derecho - Relaciones Laborales y Recursos Humanos',
       'Economía - Matemáticas y Ciencia de Datos',
       'Economía - Relaciones Internacionales',
       'Farmacia - Nutrición Humana y Dietética',
       'Gestión y Administración Pública - Economía',
       'Historia - Filología Clásica',
       'Ingeniería Informática - Matemáticas',
       'Maestro de Ed. Infantil - Maestro de Ed. Primaria',
       'Maestro de Educación Infantil - Pedagogía',
       'Maestro de Educación Primaria - Pedagogía',
       'Matemáticas - Física', 'Psicología - Logopedia',
       'Química - Bioquímica', 'Sociología - Relaciones Internacionales',
       'Turismo - Comercio', 'Bachelor of Arts in European Studies',
       'Diseño de Moda (UPM) y Comercio (UCM)',
       'Titulación Internacional en ADE (UCM-HWR Berlín)',
       'Titulación Internacional en Derecho (UCM-Sorbonne)',
       'Titulación Internacional en Economía (UCM-Sorbonne)',
       'Maestro de Educación Infantil - Maestro de Educación Primaria',
       'Estudios Clásicos y de la Antigüedad',
       'Estudios de Asia y África (Árabe)',
       'Estudios de Asia y África (Chino)',
       'Estudios de Asia y África (Japonés)',
       'Estudios Hispánicos: Lengua Española y sus Literaturas',
       'Historia y Ciencias de la Música y Tecnología Musical',
       'Lenguas Modernas, Cultura y Comunicación-Español',
       'Lenguas Modernas, Cultura y Comunicación-Francés',
       'Lenguas Modernas, Cultura y Comunicación-Inglés',
       'Traducción e Interpretación (Francés)',
       'Traducción e Interpretación (Inglés)', 'Ciencias Ambientales',
       'Enfermería (Facultad Medicina UAM)',
       'Análisis de Datos en la Empresa / Business Analytics',
       'Ciencias de la Actividad Física y del Deporte',
       'Ciencia Política y Administración Pública',
       'Ciencia Política y Administración Pública - Mención en Gobierno y dirección pública',
       'Ciencia Política y Administración Pública - Mención en Relaciones internacionales y Unión Europea',
       'Derecho - Mención en Derecho de la energía y del medio ambiente',
       'Derecho - Mención en Derecho de los negocios internacionales',
       'Derecho - Mención en Derecho digital y de las tecnologías',
       'Derecho - Mención en Derechos humanos y justicia social',
       'Economía (Grupo bilingüe: español/inglés)', 'Economía y Finanzas',
       'Estudios Internacionales',
       'Geografía, Geotecnologías y Sostenibilidad Territorial',
       'Gestión Aeronáutica', 'Maestro en Educación Infantil',
       'Maestro en Educación Primaria', 'Ciencia e Ingeniería de Datos',
       'Ingeniería Biomédica',
       'Ingeniería de Tecnologías y Servicios de Telecomunicación',
       'Programa Académico en Master en Ingeniería de Telecomunicación vía Grado en Ingeniería de Tecnologías y Servicios de Telecomunicación',
       'Programa Académico en Master en Ingeniería Informática vía Grado en Ingeniería Informática',
       'Ciencias Ambientales - Geografía y Ordenación del Territorio',
       'Derecho - Administración y Dirección de Empresas',
       'Derecho - Ciencia Política y Administración Pública',
       'Estudios Internacionales - Estudios de Asia y África (Árabe)',
       'Filosofía - Historia',
       'Filosofía - Historia y CC. de la Música y Tecnología Musical',
       'Historia - Estudios Internacionales',
       'Historia del Arte - Estudios Clásicos y de la Antigüedad',
       'Historia del Arte - Historia',
       'Maestro en Educación Infantil - Maestro en Educación Primaria',
       'Nutrición Humana y Dietética - Ciencia y Tecnología de los Alimentos',
       'Traducción e Interpretación (Francés) - Lenguas Modernas, Cultura y Comunicación (Francés)',
       'Ciencia, Tecnología y Humanidades (UAB, UAM y UC3M)',
       'Ciencias (UAB, UAM y UC3M)',
       'Filosofía, Política y Economía (UAB, UAM, UC3M y UPF)',
       'Diseño y Gestión de Proyectos Transmedia',
       'Enfermería (Campus Villalba)', 'Estudios Hispánicos',
       'Humanidades', 'Lenguas Modernas y Traducción',
       'Lenguas Modernas y Traducción (Guadalajara)',
       'Criminalística: Ciencias y Tecnologías Forenses',
       'Física e Instrumentación Espacial', 'Biología Sanitaria',
       'Enfermería (Guadalajara)',
       'Administración y Dirección de Empresas (Guadalajara)',
       'Comunicación Audiovisual (Guadalajara)', 'Finanzas',
       'Economía y Negocios Internacionales',
       'Economía y Negocios Internacionales (docencia en inglés)',
       'Magisterio de Educación Infantil (Guadalajara)',
       'Magisterio de Educación Primaria (bilingüe) (docencia en inglés) (Guadalajara)',
       'Magisterio de Educación Primaria (Guadalajara)',
       'Turismo (Guadalajara)',
       'Arquitectura Técnica y Edificación (Guadalajara)',
       'Fundamentos de Arquitectura y Urbanismo',
       'Ingeniería Electrónica y Automática Industrial',
       'Ingeniería en Sistemas de Información',
       'Ingeniería en Sistemas de Telecomunicación',
       'Ingeniería en Tecnologías de Telecomunicación',
       'Ingeniería de Telecomunicaciones',
       'Ingeniería en Tecnologías Industriales',
       'Ingeniería en Tecnologías Industriales + Master Universitario en Ingeniería Industrial',
       'Ingeniería Telemática', 'Matemáticas y Computación (Guadalajara)',
       'Humanidades - Magisterio en Educación Primaria',
       'Ingeniería Informática - Administración y Dirección de Empresas',
       'Ingeniería Electrónica de Comunicaciones - Ing. Electrónica y Automática Industrial',
       'Magisterio de Educación Infantil - Magisterio de Educación Primaria (Guadalajara)',
       'Turismo - Admón. y Dirección de Empresas (Guadalajara)',
       'Magisterio de Educación Infantil',
       'Magisterio de Educación Infantil (bilingüe) (docencia en inglés)',
       'Magisterio de Educación Infantil (semipresencial)',
       'Magisterio de Educación Primaria',
       'Magisterio de Educación Primaria (bilingüe) (docencia en inglés)',
       'Magisterio de Educación Primaria (Semipresencial)',
       'Estudios Culturales (bilingüe)', 'Neurociencia (en inglés)',
       'Administración de Empresas (español o inglés)',
       'Administración de Empresas (Colmenarejo)',
       'Ciencias Políticas (español o bilingüe)',
       'Comunicación Audiovisual (español o bilingüe)',
       'Derecho (Colmenarejo)', 'Economía (español o inglés)',
       'Empresa y Tecnología (en inglés)', 'Estadística y Empresa',
       'Estudios Internacionales (en inglés)',
       'Finanzas y Contabilidad (español o inglés)',
       'Gestión de la Información y Contenidos Digitales',
       'Historia y Política (bilingüe)',
       'Periodismo (español o bilingüe)', 'Relaciones Laborales y Empleo',
       'Sociología (español o bilingüe)',
       'Ciencia e Ingeniería de Datos (en inglés)',
       'Ingeniería Aeroespacial (en inglés)',
       'Ingeniería Biomédica (en inglés)',
       'Ingeniería de Comunicaciones Móviles y Espaciales (español o bilingüe)',
       'Ingeniería de la Energía (en inglés)',
       'Ingeniería de Sonido e Imagen (español o bilingüe)',
       'Ingeniería Eléctrica (español o bilingüe)',
       'Ingeniería Electrónica Industrial y Automática (español o bilingüe)',
       'Ingeniería en Tecnologías de Telecomunicación (español o bilingüe)',
       'Ingeniería en Tecnologías Industriales (español o bilingüe)',
       'Ingeniería Física (en inglés)',
       'Ingeniería Informática (español, bilingüe o inglés)',
       'Ingeniería Informática (Colmenarejo)',
       'Ingeniería Mecánica (español o bilingüe)',
       'Ingeniería Robótica (en inglés)',
       'Ingeniería Telemática (español o bilingüe)',
       'Matemática Aplicada y Computación (en inglés)',
       'Programa Académico de Ingeniería Informática vía Grado en Ing. Informática (bilingüe)',
       'Programa Académico de Ingeniería de Telecomunicación vía Grado en Ing. en Tecnologías de Telecomunicación (bilingüe)',
       'Programa Académico de Ingeniería Industrial vía Grado en Ing. en Tecnologías Industriales (bilingüe-español)',
       'Ciencias Políticas y Sociología',
       'Ciencia e Ingeniería de Datos e Ingeniería en Tecnologías de Telecomunicación (bilingüe)',
       'Derecho y Administración de Empresas (español o bilingüe)',
       'Derecho y Administración de Empresas (Colmenarejo)',
       'Derecho y Ciencias Políticas',
       'Derecho y Economía (español o bilingüe)',
       'Estudios Internacionales y Administración de Empresas (en inglés)',
       'Estudios Internacionales y Ciencias Políticas (bilingüe)',
       'Estudios Internacionales y Derecho (bilingüe)',
       'Estudios Internacionales y Economía (en inglés)',
       'Ingeniería Física e Ingeniería en Tecnologías Industriales (bilingüe)',
       'Ingeniería Informática y Administración de Empresas (Colmenarejo)',
       'Ingeniería Informática y Administración de Empresas (Leganes-Getafe)',
       'Periodismo y Comunicación Audiovisual (español o bilingüe)',
       'Periodismo y Humanidades',
       'Filosofía, Política y Economía (bilingüe) (UAB, UAM, UC3M y UPF)',
       'Ciencias Agrarias y Bioeconomía',
       'Ciencias de la Actividad Física y del Deporte (INEF)',
       'Arquitecto/a (PARS)', 'Arquitectura Naval / Ingeniería Marítima',
       'Biotecnología',
       'Ciencia de Datos e Inteligencia Artificial (Campus de Montegancedo)',
       'Ciencia de Datos e Inteligencia Artificial (Campus Sur)',
       'Edificación', 'Fundamentos de la Arquitectura',
       'Gestión y Operaciones del Transporte Aéreo',
       'Ingeniería Aeroespacial', 'Ingeniero/a Aeronáutico/a (PARS)',
       'Ingeniería Agrícola', 'Ingeniero/a Agrónomo/a (PARS)',
       'Ingeniería Agroambiental', 'Ingeniería Alimentaria',
       'Ingeniero/a Biomédico/a (PARS)', 'Ingeniería Civil y Territorial',
       'Ingeniería Civil y Territorial (Retiro)',
       'Ingeniero/a de Caminos, Canales y Puertos (PARS)',
       'Ingeniería de la Energía',
       'Ingeniería de las Tecnologías de la Información Geoespacial',
       'Ingeniero/a de Materiales (PARS)', 'Ingeniero/a de Minas (PARS)',
       'Ingeniero/a de Montes (PARS)', 'Ingeniería de Organización',
       'Ingeniería de Sistemas de Telecomunicación',
       'Ingeniería de Sonido e Imagen',
       'Ingeniero/a de Telecomunicación (PARS)',
       'Ingeniería del Medio Natural', 'Ingeniero/a del Software (PARS)',
       'Ingeniería Eléctrica',
       'Ingeniería Electrónica Industrial y Automática',
       'Ingeniería en Diseño Industrial y Desarrollo de Producto',
       'Ingeniero/a Sistemas Informáticos Distribuidos y Embebidos (PARS)',
       'Ingeniería en Tecnología Minera / Ing. Geológica / Ing. Mineralúrgica y Metalúrgica de las Materias Primas / Ing. en Recursos Energéticos, Combustibles y Explosivos',
       'Ingeniería en Tecnologías Aeroespaciales',
       'Ingeniería en Tecnologías Ambientales', 'Ingeniería Forestal',
       'Ingeniería Geomática', 'Ingeniero/a Industrial (PARS)',
       'Ingeniero/a Informática (PARS)', 'Ingeniería Mecánica',
       'Ingeniero/a Naval y Oceánica (PARS)',
       'Ingeniería Química (Castellana)',
       'Ingeniería Química (Embajadores)',
       'Ingeniería y Sistemas de datos (Campus Moncloa)',
       'Matemáticas e Informática', 'Sistemas de Información',
       'Tecnologías para la Sociedad de la Información',
       'Edificación - Administración y Dirección de Empresas',
       'Ingeniería Civil y Territorial - Administración y Dirección de Empresas',
       'Ingeniería Eléctrica - Ingeniería Electrónica Industrial y Automática',
       'Ingeniería Electrónica de Comunicaciones - Ingeniería Telemática',
       'Ingeniería en Diseño Industrial y Desarrollo de Producto - Ingeniería Mecánica',
       'Ingeniería Geomática e Ingeniería de las Tecnologías de la Información Geoespacial (Campus Sur)',
       'Ingeniería y Sistemas de Datos e Ingeniería Telemática (Campus Sur)',
       'Diseño de Moda', 'Artes Visuales y Danza (Fuenlabrada)',
       'Bellas Artes (Aranjuez)',
       'Diseño Integral y Gestión de la Imagen (Aranjuez)',
       'Diseño Integral y Gestión de la Imagen (Madrid)',
       'Diseño y Gestión de Moda (Aranjuez)', 'Filosofía (Fuenlabrada)',
       'Historia (Fuenlabrada)',
       'Lengua y Literatura Española (Fuenlabrada)',
       'Paisajismo (Fuenlabrada)',
       'Traducción e Interpretación (Aranjuez)',
       'Traducción e Interpretación (Móstoles)', 'Biología (Móstoles)',
       'Ciencia y Tecnología de los Alimentos (Móstoles)',
       'Ciencias Ambientales (Móstoles)',
       'Ciencias Experimentales (Móstoles)', 'Matemáticas (Móstoles)',
       'Nanociencia y Nanotecnología (Móstoles)',
       'Recursos Hídricos (Móstoles)', 'Enfermería (Alcorcón)',
       'Farmacia (Alcorcón)', 'Fisioterapia (Alcorcón)',
       'Medicina (Alcorcón)', 'Odontología (Alcorcón)',
       'Psicología (Alcorcón)', 'Terapia Ocupacional (Alcorcón)',
       'Ciencia e Ingeniería de Datos (Fuenlabrada)',
       'Diseño y Desarrollo de Videojuegos (Madrid)',
       'Diseño y Desarrollo de Videojuegos (Móstoles)',
       'Fundamentos de la Arquitectura (Fuenlabrada)',
       'Ingeniería Aeroespacial en Aeronavegación (Fuenlabrada)',
       'Ingeniería Aeroespacial en Transporte y Aeropuertos (Fuenlabrada)',
       'Ingeniería Aeroespacial en Vehículos Aeroespaciales (Fuenlabrada)',
       'Ingeniería Ambiental (Móstoles)',
       'Ingeniería Biomédica (Fuenlabrada)',
       'Ingeniería Biomédica (inglés) (Fuenlabrada)',
       'Ingeniería de Computadores (Móstoles)',
       'Ingeniería de la Ciberseguridad (Móstoles)',
       'Ingeniería de la Energía (Móstoles)',
       'Ingeniería de Materiales (Móstoles)',
       'Ingeniería de Robótica Software (Fuenlabrada)',
       'Ingeniería de Tecnologías Industriales (Móstoles)',
       'Ingeniería del Software (Móstoles)',
       'Ingeniería Electrónica Industrial y Automática (Móstoles)',
       'Ingeniería en Organización Industrial (Móstoles)',
       'Ingeniería en Organización Industrial (Vicálvaro)',
       'Ingeniería en Sistemas Audiovisuales y Multimedia (Fuenlabrada)',
       'Ingeniería en Sistemas de Telecomunicación (Fuenlabrada)',
       'Ingeniería en Tecnologías de la Telecomunicación (Fuenlabrada)',
       'Ingeniería en Telemática (Fuenlabrada)',
       'Ingeniería Informática (Móstoles)',
       'Ingeniería Informática (Vicálvaro)',
       'Ingeniería Mecánica (Móstoles)', 'Ingeniería Química (Móstoles)',
       'Inteligencia Artificial (Móstoles)',
       'Administración y Dirección de Empresas (Fuenlabrada)',
       'Administración y Dirección de Empresas (Inglés) (Vicálvaro)',
       'Administración y Dirección de Empresas (Móstoles)',
       'Administración y Dirección de Empresas (Vicálvaro)',
       'Administración y Dirección de Empresas A Distancia (Vicálvaro)',
       'Ciencia Política y Gestión Pública (Fuenlabrada)',
       'Ciencia Política y Gestión Pública (Vicálvaro)',
       'Ciencia, Gestión e Ingeniería de Servicios (Madrid)',
       'Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) (Vicálvaro)',
       'Ciencias de la Actividad Física y del Deporte (Fuenlabrada)',
       'Comunicación Audiovisual (Fuenlabrada)',
       'Comunicación Audiovisual (Vicálvaro)',
       'Comunicación Digital (Fuenlabrada)',
       'Contabilidad y Finanzas (Fuenlabrada)',
       'Contabilidad y Finanzas (Móstoles)',
       'Contabilidad y Finanzas (A Distancia) (Vicálvaro)',
       'Contabilidad y Finanzas (Vicálvaro)', 'Criminología (Alcorcón)',
       'Criminología (Vicálvaro)', 'Derecho (Fuenlabrada)',
       'Derecho (Móstoles)', 'Derecho (Vicálvaro)',
       'Derecho (Semipresencial) (Vicálvaro)',
       'Dirección y Gestión de Empresas en el Ámbito Digital (Vicálvaro)',
       'Economía (Fuenlabrada)', 'Economía (Inglés) (Madrid)',
       'Economía (Móstoles)', 'Economía (Vicálvaro)',
       'Economía Financiera y Actuarial (Móstoles)',
       'Economía Financiera y Actuarial (Vicálvaro)',
       'Educación Infantil (Fuenlabrada)',
       'Educación Infantil (Inglés) (Vicálvaro)',
       'ADE (A distancia) (Vicálvaro) - Ciencia, Gestión e Ingeniería de Servicios (Presencial) (Madrid)',
       'ADE (Presencial) - Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) (Vicálvaro)',
       'Administración y Dirección de Empresas - Derecho (Fuenlabrada)',
       'Administración y Dirección de Empresas - Derecho (Madrid)',
       'Administración y Dirección de Empresas - Derecho (Móstoles)',
       'Administración y Dirección de Empresas - Derecho (Vicálvaro)',
       'Administración y Dirección de Empresas - Marketing (Vicálvaro)',
       'Bellas Artes - Diseño Integral y Gestión de la Imagen (Aranjuez)',
       'Bellas Artes (Presencial) (Aranjuez) - Turismo (Semipresencial) (Vicálvaro)',
       'Ciencia Política y Gestión Pública - Derecho (Fuenlabrada)',
       'Ciencia Política y Gestión Pública - Derecho (Vicálvaro)',
       'Ciencia Política y Gestión Pública - Economía (Fuenlabrada)',
       'Ciencia Política y Gestión Pública - Economía (Vicálvaro)',
       'Ciencia Política y Gestión Pública - Periodismo (Fuenlabrada)',
       'Ciencia Política y Gestión Pública - Periodismo (Vicálvaro)',
       'Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) - Ingeniería en Organización Industrial (Presencial) (Vicálvaro)',
       'Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) - Marketing (Presencial) (Vicálvaro)',
       'Ciencia, Gestión e Ingeniería de Servicios (Semipresencial) - Turismo (Presencial) (Vicálvaro)',

In [81]:
def clasificar_titulacion(titulacion):
    biosanitario = ["Medicina", "Enfermería", "Psicología", "Farmacia", "Fisioterapia", "Nutrición", "Veterinaria", "Odontología", "Terapia Ocupacional", "Logopedia", "Podología", "Neurociencia", "Óptica", "Optometría"]
    ciencias = ["Biología", "Química", "Física", "Matemáticas", "Geología", "Ciencias Ambientales", "Estadística", "Bioquímica", "Ciencia", "Nanociencia", "Astronomía", "Biotecnología", "Geografía", "Recursos Hídricos"]
    tecnologico_ingenierias = ["Ingeniería", "Tecnología", "Computadores", "Telecomunicación", "Informática", "Electrónica", "Aeroespacial", "Materiales", "Robótica", "Videojuegos", "Desarrollo", "Industrial", "Arquitectura", "Edificación", "Sistemas de Información", "PARS", "Sistemas Informáticos Distribuidos", "Inteligencia Artificial", "Análisis de Datos", "Computación"]
    ciencias_sociales_juridicas = ["Derecho", "Economía", "Administración", "Relaciones Internacionales", "Sociología", "Ciencias Políticas", "Antropología", "Criminología", "Trabajo Social", "Educación", "Pedagogía", "Finanzas", "Contabilidad", "ADE", "Marketing", "Protocolo", "Comercio", "Periodismo", "Publicidad", "Relaciones Laborales", "Turismo", "Información y Documentación", "Gestión de la Información", "Dirección y Gestión", "Gestión Aeronáutica", "Gestión y Operaciones del Transporte Aéreo", "European Studies"]
    humanidades_artes = ["Historia", "Arte", "Filosofía", "Lingüística", "Literatura", "Diseño", "Bellas Artes", "Arqueología", "Estudios", "Traducción", "Música", "Teatro", "Cine", "Danza", "Humanidades", "Estudios Clásicos", "Estudios Hispánicos", "Filología", "Conservación", "Patrimonio", "Musicología", "Composición", "Audiovisual", "Fotografía", "Lenguas Modernas", "Paisajismo", "Comunicación Digital"]
    
    if "Maestro de Ed. Infantil" in titulacion or "Maestro de Educación Primaria" in titulacion:
        return "Ciencias Sociales-Jurídicas"
    if any(keyword in titulacion for keyword in biosanitario):
        return "Biosanitario"
    elif any(keyword in titulacion for keyword in ciencias):
        return "Ciencias"
    elif any(keyword in titulacion for keyword in tecnologico_ingenierias):
        return "Tecnológico-Ingenierías"
    elif any(keyword in titulacion for keyword in ciencias_sociales_juridicas):
        return "Ciencias Sociales-Jurídicas"
    elif any(keyword in titulacion for keyword in humanidades_artes):
        return "Humanidades y Artes"
    else:
        return "Sin Clasificar"


df_notas_corte_total['Especialidad'] = df_notas_corte_total['TITULACIONES DE GRADO'].apply(clasificar_titulacion)
df_notas_corte_total.head()

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro,Especialidad
0,0001,Arqueología,5.000,Universidad Complutense de Madrid,Humanidades y Artes
1,0002,Bellas Artes,10.115,Universidad Complutense de Madrid,Humanidades y Artes
2,0019,Ciencias de las Religiones,5.000,Universidad Complutense de Madrid,Ciencias
3,0004,Conservación y Restauración del Patrimonio Cul...,10.100,Universidad Complutense de Madrid,Humanidades y Artes
4,0005,Diseño,11.818,Universidad Complutense de Madrid,Humanidades y Artes

In [82]:
valores_unicos = df_notas_corte_total['Especialidad'].unique()
valores_unicos

array(['Humanidades y Artes', 'Ciencias', 'Biosanitario',
       'Tecnológico-Ingenierías', 'Ciencias Sociales-Jurídicas'],
      dtype=object)

In [83]:
df_notas_corte_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Código                 572 non-null    object
 1   TITULACIONES DE GRADO  572 non-null    object
 2   Grupo 1 Ord.           572 non-null    object
 3   Centro                 572 non-null    object
 4   Especialidad           572 non-null    object
dtypes: object(5)
memory usage: 22.5+ KB

In [84]:
df_notas_corte_total['Grupo 1 Ord.'] = df_notas_corte_total['Grupo 1 Ord.'].astype(float)

In [85]:
def convertir_nota_a_escala_cero_a_uno(nota):
    return round((nota * 10) / 14, 3) # redondeo a 3 decimales


df_notas_corte_total['NOTA FINAL'] = df_notas_corte_total['Grupo 1 Ord.'].apply(convertir_nota_a_escala_cero_a_uno)

# PARA QUE NO HAYA SUSPENSOS
# Asignar valor de 5.0 a las filas donde "NOTA FINAL" es menor que 5.0 
df_notas_corte_total.loc[df_notas_corte_total['NOTA FINAL'] < 5.0, 'NOTA FINAL'] = 5.0


df_notas_corte_total.head()

,Código,TITULACIONES DE GRADO,Grupo 1 Ord.,Centro,Especialidad,NOTA FINAL
0,0001,Arqueología,5.000,Universidad Complutense de Madrid,Humanidades y Artes,5.000
1,0002,Bellas Artes,10.115,Universidad Complutense de Madrid,Humanidades y Artes,7.225
2,0019,Ciencias de las Religiones,5.000,Universidad Complutense de Madrid,Ciencias,5.000
3,0004,Conservación y Restauración del Patrimonio Cul...,10.100,Universidad Complutense de Madrid,Humanidades y Artes,7.214
4,0005,Diseño,11.818,Universidad Complutense de Madrid,Humanidades y Artes,8.441

In [86]:
df_notas_corte_total['Especialidad'].unique()

array(['Humanidades y Artes', 'Ciencias', 'Biosanitario',
       'Tecnológico-Ingenierías', 'Ciencias Sociales-Jurídicas'],
      dtype=object)

In [87]:
df_notas_corte_total['NOTA FINAL'].unique()

array([5.   , 7.225, 7.214, 8.441, 5.413, 5.324, 7.39 , 5.091, 7.385,
       8.945, 6.234, 8.614, 8.786, 8.546, 7.24 , 8.41 , 8.417, 8.341,
       6.768, 9.475, 7.473, 9.126, 5.476, 6.507, 7.349, 6.811, 8.625,
       7.331, 6.921, 9.056, 6.347, 7.429, 6.334, 7.796, 8.922, 7.967,
       7.418, 7.969, 8.074, 5.901, 7.49 , 8.285, 6.339, 6.579, 7.321,
       5.999, 6.508, 7.02 , 6.757, 7.508, 6.571, 5.41 , 7.738, 8.484,
       5.776, 5.424, 8.349, 7.821, 7.378, 7.064, 5.768, 7.296, 9.268,
       9.264, 8.991, 6.357, 9.661, 8.39 , 7.079, 8.401, 9.811, 7.573,
       9.27 , 8.014, 5.341, 6.236, 8.213, 6.919, 8.686, 6.043, 6.829,
       7.102, 8.799, 6.331, 5.214, 8.615, 8.563, 7.115, 8.451, 9.391,
       7.286, 7.671, 7.619, 8.507, 7.857, 5.939, 6.414, 8.699, 7.304,
       6.526, 8.273, 7.949, 7.008, 6.349, 8.159, 8.15 , 7.76 , 6.536,
       7.269, 8.002, 9.008, 6.939, 7.532, 7.475, 8.321, 8.196, 6.13 ,
       7.034, 8.739, 6.586, 9.36 , 8.897, 9.456, 7.793, 8.087, 8.984,
       5.75 , 8.73 , 7.831, 7.698, 7.631, 5.014, 7.804, 8.839, 8.589,
       7.346, 8.929, 7.779, 8.4  , 8.296, 8.293, 8.161, 9.359, 7.365,
       6.316, 6.399, 6.143, 6.332, 6.359, 8.513, 7.724, 6.252, 6.136,
       6.806, 6.046, 7.661, 6.561, 5.764, 7.276, 5.908, 5.664, 7.196,
       7.581, 8.242, 7.776, 5.724, 8.106, 7.865, 7.529, 8.162, 6.851,
       7.681, 5.369, 5.815, 7.01 , 9.417, 8.619, 8.146, 7.043, 7.822,
       8.554, 8.026, 8.319, 9.079, 8.381, 9.071, 8.192, 7.599, 7.124,
       6.786, 5.333, 5.288, 8.184, 9.5  , 9.161, 7.357, 8.29 , 6.833,
       7.742, 7.689, 8.494, 9.42 , 7.843, 7.561, 7.097, 9.029, 8.456,
       8.893, 9.471, 6.26 , 8.609, 9.311, 8.455, 8.429, 9.099, 9.545,
       9.26 , 9.589, 9.38 , 9.491, 8.426, 8.855, 8.377, 5.714, 6.814,
       9.117, 8.632, 6.742, 9.214, 7.536, 9.232, 8.383, 5.193, 8.097,
       8.224, 8.875, 9.413, 6.413, 9.074, 7.036, 6.633, 7.906, 7.224,
       7.216, 6.145, 8.916, 6.502, 5.519, 6.629, 7.232, 8.339, 7.439,
       6.117, 7.732, 8.867, 6.51 , 5.796, 8.768, 8.556, 9.52 , 8.482,
       8.49 , 8.392, 7.895, 8.367, 6.607, 6.25 , 7.786, 6.337, 9.211,
       8.435, 6.163, 6.724, 8.489, 7.531, 7.163, 5.493, 5.231, 8.436,
       8.311, 8.464, 8.571, 8.01 , 9.344, 9.096, 7.579, 6.679, 7.528,
       7.119, 7.538, 8.61 , 8.521, 8.744, 8.936, 8.704, 6.734, 7.752,
       7.5  , 6.474, 7.454, 7.207, 7.26 , 8.018, 7.934, 5.464, 6.574,
       6.848, 6.367, 7.611, 7.341, 8.021, 6.929, 6.494, 6.714, 6.429,
       6.124, 7.909, 6.617, 6.893, 6.707, 6.2  , 6.392, 7.716, 7.206,
       6.739, 6.699, 5.907, 7.651, 7.136, 6.618, 6.306, 6.794, 6.646,
       7.633, 6.696, 7.294, 8.919, 8.913, 7.125, 5.643, 7.139, 7.431,
       8.557, 6.834, 7.   , 9.18 , 8.179, 9.182, 8.966, 9.681, 9.591,
       6.895, 9.261, 7.191, 8.189, 8.633, 8.357, 8.707, 8.046, 8.186,
       8.561, 7.778, 8.252, 8.732, 8.088, 7.044, 8.005, 7.288, 9.143,
       9.001, 8.268, 7.554, 8.133, 7.849, 8.024, 7.544, 7.839, 6.01 ,
       6.529, 6.991, 7.302, 9.349, 9.063, 8.762, 9.144, 9.376, 7.091,
       7.663, 5.982])

In [88]:
# df_notas_corte_total.to_csv('notas_corte_total.csv', index=False, encoding='utf-8')